### ISSUE TITLE
Alias failed with error

### ISSUE THREAD

**Issue by ToksT** [danbooru/danbooru#2202]
A delayed job for the alias `wink -> one_eye_closed` failed with an error, and appears to be backing up thousands of other delayed jobs.

The error (apparently related to a deadlock of some kind):

```
PG::StringDataRightTruncation: ERROR:  value too long for type character varying(255)
: UPDATE "tag_aliases" SET "status" = 'error: PG::TRDeadlockDetected: ERROR:  deadlock detected
DETAIL:  Process 17551 waits for ShareLock on transaction 34627462; blocked by process 17631.
Process 17631 waits for ShareLock on transaction 34627471; blocked by process 17629.
Process 17629 waits for ExclusiveLock on tuple (15070,34) of relation 17154 of database 16386; blocked by process 17551.
HINT:  See server log for query details.
: UPDATE "tags" SET post_count = post_count - 1 WHERE "tags"."name" IN (''wink'')' WHERE "tag_aliases"."id" = 12228
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `async_exec'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `block in exec_no_cache'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activesupport-4.1.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `exec_no_cache'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:157:in `exec_delete'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:111:in `update'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/relation.rb:327:in `update_all'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/persistence.rb:278:in `update_columns'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/activerecord-4.1.0/lib/active_record/persistence.rb:253:in `update_column'
/var/www/danbooru2/releases/20140618011344/app/models/tag_alias.rb:83:in `rescue in process!'
/var/www/danbooru2/releases/20140618011344/app/models/tag_alias.rb:76:in `process!'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/performable_method.rb:26:in `perform'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/backend/base.rb:102:in `invoke_job'
(eval):3:in `block in invoke_job_with_newrelic_transaction_trace'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:335:in `perform_action_with_newrelic_trace'
(eval):2:in `invoke_job_with_newrelic_transaction_trace'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/home/albert/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:207:in `block in run'
/home/albert/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:206:in `run'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:190:in `block in work_off'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:189:in `times'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:189:in `work_off'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/home/albert/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:151:in `loop'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:151:in `block in start'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:78:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:78:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:78:in `block in add'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/worker.rb:150:in `start'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/command.rb:104:in `run'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/command.rb:92:in `block in run_process'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/command.rb:90:in `run_process'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/command.rb:83:in `block in daemonize'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/command.rb:81:in `times'
/var/www/danbooru2/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.1/lib/delayed/command.rb:81:in `daemonize'
script/delayed_job:5:in `<main>'
```

**Comment by r888888888** [comment]
I see the "UPDATE "tags" SET post_count = post_count - 1" errors pretty often. It's usually just contention on the tags table with a bunch of updates and can't really be traced to a specific feature.
