### ISSUE TITLE
Exception on IQDB query with URL parameter

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4023]
This issue was noticed when trying out the following image URL.

- Image URL: https://pbs.twimg.com/media/BuPRYSmIEAAIa1U.jpg:medium
- IQDB URL: https://danbooru.donmai.us/iqdb_queries.json?url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FBuPRYSmIEAAIa1U.jpg%3Amedium

```json
  {
    "success": false,
    "message": "no implicit conversion of String into Integer",
    "backtrace": ["app/logical/iqdb_proxy.rb:15:in `[]'","app/logical/iqdb_proxy.rb:15:in `block in decorate_posts'","app/logical/iqdb_proxy.rb:13:in `each'","app/logical/iqdb_proxy.rb:13:in `map'","app/logical/iqdb_proxy.rb:13:in `decorate_posts'","app/logical/iqdb_proxy.rb:9:in `query'","app/controllers/iqdb_queries_controller.rb:8:in `show'"]
  }
```

However, the exception only occurs when using the URL parameter. When using the URL text input on the ``/iqdb_queries`` HTML endpoint which uses the callback functionality instead, it correctly identifies the correct image/post.

I'm not sure if this is relevant or not, but the medium size of that image is the only one that is still working.  All of the other images sizes give HTTP 404 responses.

- Bad: https://pbs.twimg.com/media/BuPRYSmIEAAIa1U.jpg:orig
- Bad: https://pbs.twimg.com/media/BuPRYSmIEAAIa1U.jpg:large
- Good: https://pbs.twimg.com/media/BuPRYSmIEAAIa1U.jpg:medium
- Bad: https://pbs.twimg.com/media/BuPRYSmIEAAIa1U.jpg:small

**Comment by BrokenEagle** [comment]
This should be fixed now that #4481 has been merged. The problem was is that the **url** parameter selects the smallest image available, which on Twitter is the `:small` size, which is a bad image link.  Users can now just use the image URL sizes that work with the **image_url** parameter.
