### ISSUE TITLE
Bookmarklet fails on certain Nicoseiga posts

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4135]
http://seiga.nicovideo.jp/seiga/im9208126

```
ActionView::Template::Error exception raised
image url not found for (http://seiga.nicovideo.jp/seiga/im9208126, http://seiga.nicovideo.jp/seiga/im9208126)

app/logical/sources/strategies/nico_seiga.rb:48:in `image_urls'
app/logical/sources/strategies/base.rb:75:in `image_url'
app/views/uploads/_image.html.erb:3:in `_app_views_uploads__image_html_erb___998738582218535715_47013196888600'
app/views/uploads/new.html.erb:14:in `_app_views_uploads_new_html_erb___1956998059314765135_47013197004820'
app/controllers/uploads_controller.rb:12:in `new'
```

Probably comes from this post being age-restricted (R-15).

**Comment by evazion** [comment]
Another:

https://seiga.nicovideo.jp/seiga/im520647
https://seiga.nicovideo.jp/api/illust/info?id=520647

This one is because the post has no user id.
