### ISSUE TITLE
Saved searches fail when search returns zero results

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4153]
```
Error
ERR wrong number of arguments for 'sadd' command

Details
Redis::CommandError exception raised
app/models/saved_search.rb:101:in `block in populate'
app/logical/current_user.rb:10:in `scoped'
app/logical/current_user.rb:38:in `as_system'
app/models/saved_search.rb:97:in `populate'
app/models/saved_search.rb:30:in `block in post_ids_for'
app/models/saved_search.rb:23:in `each'
app/models/saved_search.rb:23:in `post_ids_for'
app/logical/post_query_builder.rb:77:in `block in add_saved_search_relation'
app/logical/post_query_builder.rb:73:in `each'
app/logical/post_query_builder.rb:73:in `add_saved_search_relation'
app/logical/post_query_builder.rb:221:in `build'
app/models/post.rb:1681:in `tag_match'
app/models/post.rb:1155:in `block in fast_count_search'
app/models/application_record.rb:267:in `with_timeout'
app/models/post.rb:1154:in `fast_count_search'
app/models/post.rb:1145:in `fast_count'
app/logical/post_sets/post.rb:113:in `get_post_count'
app/logical/post_sets/post.rb:125:in `posts'
app/controllers/posts_controller.rb:13:in `index'
```

https://github.com/r888888888/danbooru/blob/ffc693ef3733ce5ce9185648e688ef9345dee56f/app/models/saved_search.rb#L94-L106

`SavedSearch.populate` fails when a saved search returns zero results. We end up passing `[]` to `redis.sadd`, which doesn't work. This should have never worked to begin with, so I'm not sure why it only started happening after the last deployment.

**Comment by evazion** [comment]
Fixed in 2841f0742cab18e2899ee028bdc868e851a94715.
