### ISSUE TITLE
Exception when viewing IP addresses by user/ID

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4285]
I'm getting the following exception on my Danbooru instance:

**ActiveRecord::StatementInvalid in IpAddresses#index**
```
app/logical/pagination_extension.rb:107:in `total_count'
app/logical/pagination_extension.rb:102:in `total_pages'
app/logical/pagination_extension.rb:55:in `is_last_page?'
app/logical/pagination_extension.rb:76:in `next_page'
app/views/layouts/default.html.erb:12
app/controllers/application_controller.rb:115:in `render_error_page'
app/controllers/application_controller.rb:100:in `rescue_exception'
```
![image](https://user-images.githubusercontent.com/21149935/73812869-2a14eb00-4793-11ea-95ce-f43f028f3870.png)

The exception doesn't make too much sense with my still limited understanding, but I thought I'd post it here just in case this exception also exists on Danbooru, or if not, what can be done to resolve it for other users of this code.

**Comment by BrokenEagle** [comment]
I just saw that this was recently fixed with 6b3c541, but that's only a temp fix so I'll leave this open until that gets solved.
