### ISSUE TITLE
Just updated a few weeks old version to the latest and the layout is borked?

### ISSUE THREAD

**Issue by GlassedSilver** [danbooru/danbooru#4331]
Heya!

So just after praising the installation I managed to pull off thanks to your help I did run into an issue caused by an update for the first time. When I view any page in my local instance everything is displayed in one vertical line as if no divs were loading. (post pages don't load the image, only after clicking "view original" and then they are blurry. When viewing them "hotlinked" outside of the generated page they are crispy and clear)

When executing `bundle exec rails server --binding 192.168.2.229` I get this:

```
=> Booting Puma
=> Rails 6.0.2.1 application starting in development
=> Run `rails server --help` for more startup options
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache.rb:60: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache/redis_cache_store.rb:180: warning: The called method `initialize' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call       /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
Puma starting in single mode...
* Version 4.3.3 (ruby 2.7.0-p0), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://192.168.2.229:3000
Use Ctrl-C to stop
```

Page loads generate the same warnings. I don't see errors.

Curiously, when loading a post's page, the image isn't displayed, everything is still displayed as one vertical row (reminds you a lot of how old mobile websites used to work...).

Maybe I missed something in the update process? (my last update is a few weeks back, since my main computer took a nose dive and that kept me hella busy, now back in the game with a shiny new Ryzen build. :) )

```
    cd danbooru
    git fetch upstream
    git stash
    git merge upstream/master
    cp /var/www/danbooru2/shared/config/* ~/danbooru/config
    yarn install --check-files
    bundle install
    bundle exec rake db:create db:migrate
```
is what I ran. Any thoughts?

![Anmerkung 2020-03-07 175330](https://user-images.githubusercontent.com/1912133/76147457-9e95bf00-609c-11ea-98f6-4cacd39baad0.png)

**Comment by BrokenEagle** [comment]
Those warnings you're getting are a big nothing burger. I'm getting those as well, but they don't really mean anything other than that Rails needs to be upgraded to use the 2.7.0 version of Ruby. You can remove those warnings by prefacing any of the rails/rake commands with `RUBYOPT=-W0` at the beginning.

```
RUBYOPT=-W0 bundle exec rails server --binding 192.168.2.229
```

_On a side note, you can bind to `0.0.0.0` instead so that you don't have to keep track of the IP addresses._

As for the layout bork, that's happened to me a few times. @evazion gave me the recommendation to delete the `/node_modules` directory and rerun the `yarn --checkfiles` command, then start up the server again. You'll want to pay special attention to the output of the webpacker. I would recommend connecting to the server via SSH so that you can capture all output from the server, which will allow you to see any warnings/errors that are generated by the webpacker.

Also, the compilation by the webpacker is pretty resource intensive, so ensure that the VM/machine has enough CPU time, memory, and HD space, so that it doesn't give a timeout error.

**Comment by GlassedSilver** [comment]
So I deleted node_modules (/usr/lib/node_modules) and that didn't help. It also didn't get rebuilt? Is that expected behavior?

I paid attention to webpacker and I'm aware of it generating heavy load for a short while after initial load, but that isn't a problem. The VM has decent performance allocated to it.

For completeness' sake here's the complete output for one initial page load:

```
danbooru@ahri-vm-danbooru:~/danbooru$ bundle exec rails server --binding 192.168.2.229
=> Booting Puma
=> Rails 6.0.2.1 application starting in development
=> Run `rails server --help` for more startup options
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache.rb:60: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache/redis_cache_store.rb:180: warning: The called method `initialize' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call       /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
Puma starting in single mode...
* Version 4.3.3 (ruby 2.7.0-p0), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://192.168.2.229:3000
Use Ctrl-C to stop
[PID:1445] Started GET "/" for 192.168.2.220 at 2020-03-07 22:18:28 +0000
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.1/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.1/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.1/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
[PID:1445]    (2.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
[PID:1445] Processing by PostsController#index as HTML
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/messages/rotator.rb:28: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call     /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/messages/rotator.rb:6: warning: The called method `initialize' is defined here
[PID:1445]   User Load (9.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[PID:1445]   ↳ app/logical/session_loader.rb:83:in `load_session_user'
[PID:1445]    (2.3ms)  set statement_timeout = 60000
[PID:1445]   ↳ app/logical/session_loader.rb:44:in `set_statement_timeout'
[PID:1445]    (1.7ms)  SET STATEMENT_TIMEOUT = 1000
[PID:1445]   ↳ app/models/application_record.rb:116:in `with_timeout'
[PID:1445]    (20.6ms)  SELECT COUNT(*) FROM "posts"
[PID:1445]   ↳ app/models/post.rb:1098:in `block in fast_count_search'
[PID:1445]    (1.2ms)  SET STATEMENT_TIMEOUT = 60000
[PID:1445]   ↳ app/models/application_record.rb:122:in `with_timeout'
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache.rb:463: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache.rb:738: warning: The called method `initialize' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache.rb:150: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache/redis_cache_store.rb:387: warning: The called method `write_entry' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call   /home/danbooru/danbooru/app/models/application_record.rb:11: warning: The called method `paginate' is defined here     /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/unbound_template.rb:24: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:130: warning: The called method `initialize' is defined here
[PID:1445]   Rendering posts/index.html.erb within layouts/sidebar
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/railties/collection_cache_association_loading.rb:7: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/railties/collection_cache_association_loading.rb:12: warning: The called method `relation_from_options' is defined here
[PID:1445]   Rendered posts/partials/common/_search.html.erb (Duration: 1.9ms | Allocations: 437)
[PID:1445]   Rendered posts/partials/index/_mode_menu.html.erb (Duration: 1.1ms | Allocations: 135)
[PID:1445]   Rendered posts/partials/index/_blacklist.html.erb (Duration: 1.5ms | Allocations: 326)
[PID:1445]   Post Load (9.3ms)  SELECT "posts".* FROM "posts" WHERE (true /* PostSets::Post#posts:2 */) ORDER BY posts.id DESC LIMIT $1 OFFSET $2  [["LIMIT", 20], ["OFFSET", 0]]
[PID:1445]   ↳ app/logical/pagination_extension.rb:97:in `records'
[PID:1445]   Tag Load (15.8ms)  SELECT "tags"."name", "tags"."post_count", "tags"."category" FROM "tags" WHERE "tags"."name" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25)  <SNIP>
[PID:1445]   ↳ app/presenters/tag_set_presenter.rb:98:in `map'
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/helpers/tag_helper.rb:111: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call        /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/helpers/tag_helper.rb:44: warning: The called method `tag_string' is defined here
[PID:1445]   Rendered posts/partials/index/_options.html.erb (Duration: 1.6ms | Allocations: 228)
[PID:1445]   Rendered posts/partials/index/_related.html.erb (Duration: 2.4ms | Allocations: 577)
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/abstract_controller/helpers.rb:67: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/request_forgery_protection.rb:313: warning: The called method `form_authenticity_token' is defined here
[PID:1445]   Rendered posts/partials/index/_edit.html.erb (Duration: 70.8ms | Allocations: 16168)
[PID:1445]   Rendered posts/partials/index/_excerpt.html.erb (Duration: 2.3ms | Allocations: 773)
/home/danbooru/danbooru/app/presenters/post_presenter.rb:28: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/danbooru/app/presenters/post_presenter.rb:98: warning: The called method `preview_class' is defined here[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 3.4ms | Allocations: 1125)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 335)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 339)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 337)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 339)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 339)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 339)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 333)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.7ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 333)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 327)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 332)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 330)
[PID:1445]   Rendered posts/partials/index/_preview.html.erb (Duration: 0.6ms | Allocations: 330)
[PID:1445]   Rendered posts/partials/index/_posts.html.erb (Duration: 64.5ms | Allocations: 30537)
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.1/lib/active_model/translation.rb:67: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/i18n-1.8.2/lib/i18n.rb:195: warning: The called method `translate' is defined here
[PID:1445]   Rendered saved_searches/_interface.html.erb (Duration: 68.9ms | Allocations: 14418)
[PID:1445]   Rendered posts/partials/common/_secondary_links.html.erb (Duration: 22.0ms | Allocations: 22448)
[PID:1445]   Rendered posts/partials/index/_seo_meta_tags.html.erb (Duration: 3.5ms | Allocations: 1241)
[PID:1445]   Rendered posts/index.html.erb within layouts/sidebar (Duration: 397.7ms | Allocations: 131253)
[PID:1445]   Rendering layouts/default.html.erb
[PID:1445] [Webpacker] Everything's up-to-date. Nothing to do
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:115: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call   /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:27: warning: The called method `initialize' is defined here
[PID:1445]   NewsUpdate Exists? (3.0ms)  SELECT 1 AS one FROM "news_updates" WHERE (created_at >= '2020-02-22 22:18:29.645431') LIMIT $1  [["LIMIT", 1]]
[PID:1445]   ↳ app/views/news_updates/_listing.html.erb:2
[PID:1445]   Rendered news_updates/_listing.html.erb (Duration: 18.6ms | Allocations: 3971)
[PID:1445]    (5.2ms)  SELECT MAX("forum_topics"."updated_at") FROM "forum_topics" WHERE (min_level <= 50) AND "forum_topics"."is_deleted" = $1  [["is_deleted", false]]
[PID:1445]   ↳ app/models/user.rb:404:in `has_forum_been_updated?'
[PID:1445]   Rendered layouts/_main_links.html.erb (Duration: 28.6ms | Allocations: 7956)
[PID:1445]   Rendered static/_footer.html.erb (Duration: 2.4ms | Allocations: 527)
[PID:1445]   Rendered layouts/default.html.erb (Duration: 121.3ms | Allocations: 19633)
[PID:1445] Completed 200 OK in 885ms (Views: 507.3ms | ActiveRecord: 139.5ms | Allocations: 212954)


/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/cookies.rb:635: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call    /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/message_encryptor.rb:150: warning: The called method `encrypt_and_sign' is defined here
/home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/message_encryptor.rb:175: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call   /home/danbooru/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/messages/metadata.rb:17: warning: The called method `wrap' is defined here
```

Thanks for the tip about the IP address, however since I just command history to that command it doesn't matter either way, I never really type it out. :)

**Comment by BrokenEagle** [comment]
Make sure you run `yarn --check-files` in order to regenerate the `/node_modules` directory.

Also, another thing you can try is deleting the `/public/packs` directory. That will force a recompile which is what you really want, because you want to see what the webpacker errors are if there are any.

Also like I said previously, you should preface the rails command with `RUBYOPT=-W0` when you run commands so that you don't get any of the garbage warnings which don't mean anything. Those just clutter up what you're posting.

What you're looking for is something like the following, which is what I got after doing all of the steps I mentioned above.

https://pastebin.com/u4u8SpD6

**Comment by GlassedSilver** [comment]
> 
> 
> Make sure you run `yarn --check-files` in order to regenerate the `/node_modules` directory.
> 
> Also, another thing you can try is deleting the `/public/packs` directory. That will force a recompile which is what you really want, because you want to see what the webpacker errors are if there are any.
> 
> Also like I said previously, you should preface the rails command with `RUBYOPT=-W0` when you run commands so that you don't get any of the garbage warnings which don't mean anything. Those just clutter up what you're posting.
> 
> What you're looking for is something like the following, which is what I got after doing all of the steps I mentioned above.
> 
> https://pastebin.com/u4u8SpD6

Ah, I didn't mind too much for my own reading's sake, but you're right, it's easier when you're helping me to redact the nonsense that isn't needed. Still chuckling over the big nothing burger. :D 

Either way, I forgot to say that yes, I indeed I ran `yarn --check-files`. I did delete the other folder as well now.

node_modules is still MIA.
the public/packs folder got recreated. Webpacker compiled for a good while (around the same amount it usually took when it needed to recompile)

I'll cut all the bits that look more or less just like what you posted, however my output ends in these errors:

```
ERROR in ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css)
Module not found: Error: Can't resolve '../../../../../node_modules/typopro-web/web/TypoPRO-ComicRelief/TypoPRO-ComicRelief-Bold.woff' in '/home/danbooru/danbooru/app/javascript/src/styles/common'
 @ ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css) 5:36-140
 @ ./app/javascript/src/styles/common/fonts.css
 @ ./app/javascript/src/styles sync \.s?css(?:\.erb)?$
 @ ./app/javascript/packs/application.js

ERROR in ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css)
Module not found: Error: Can't resolve '../../../../../node_modules/typopro-web/web/TypoPRO-ComicRelief/TypoPRO-ComicRelief-Regular.woff' in '/home/danbooru/danbooru/app/javascript/src/styles/common'
 @ ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css) 4:36-143
 @ ./app/javascript/src/styles/common/fonts.css
 @ ./app/javascript/src/styles sync \.s?css(?:\.erb)?$
 @ ./app/javascript/packs/application.js

ERROR in ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css)
Module not found: Error: Can't resolve '../../../../../node_modules/typopro-web/web/TypoPRO-Kalam/TypoPRO-Kalam-Bold.woff' in '/home/danbooru/danbooru/app/javascript/src/styles/common'
 @ ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css) 29:37-129
 @ ./app/javascript/src/styles/common/fonts.css
 @ ./app/javascript/src/styles sync \.s?css(?:\.erb)?$
 @ ./app/javascript/packs/application.js

ERROR in ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css)
Module not found: Error: Can't resolve '../../../../../node_modules/typopro-web/web/TypoPRO-Kalam/TypoPRO-Kalam-Regular.woff' in '/home/danbooru/danbooru/app/javascript/src/styles/common'
 @ ./app/javascript/src/styles/common/fonts.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/styles/common/fonts.css) 28:37-132
 @ ./app/javascript/src/styles/common/fonts.css
 @ ./app/javascript/src/styles sync \.s?css(?:\.erb)?$
 @ ./app/javascript/packs/application.js

[PID:8808]   NewsUpdate Exists? (2.0ms)  SELECT 1 AS one FROM "news_updates" WHERE (created_at >= '2020-02-23 17:13:15.368915') LIMIT $1  [["LIMIT", 1]]
[PID:8808]   ↳ app/views/news_updates/_listing.html.erb:2
[PID:8808]   Rendered news_updates/_listing.html.erb (Duration: 29.1ms | Allocations: 6124)
[PID:8808]    (2.3ms)  SELECT MAX("forum_topics"."updated_at") FROM "forum_topics" WHERE (min_level <= 50) AND "forum_topics"."is_deleted" = $1  [["is_deleted", false]]
[PID:8808]   ↳ app/models/user.rb:404:in `has_forum_been_updated?'
[PID:8808]   Rendered layouts/_main_links.html.erb (Duration: 23.4ms | Allocations: 7956)
[PID:8808]   Rendered static/_footer.html.erb (Duration: 1.4ms | Allocations: 527)
[PID:8808]   Rendered layouts/default.html.erb (Duration: 38818.2ms | Allocations: 23822)
[PID:8808] Completed 200 OK in 39414ms (Views: 39111.3ms | ActiveRecord: 73.8ms | Allocations: 215775)
```

So... finally some errors, something to tackle! I'll try to research this myself now and post the results of my findings if I come up with any, otherwise I'll be happy for any assistance. As weird as it sounds, I'm kinda glad these errors come up, so I can familiarize myself with deployments of ruby apps in general and of course solidify my maintanence know how for my danbooru instance in particular. :) Gotta think of this as positive teachings I think.

**Comment by GlassedSilver** [comment]
### RESOLVED! :) \*

...well at least the pages generate fine again.

`yarn install --force` (in ~/danbooru/)
then delete packs: `rm -rf ~/danbooru/public/packs/`
then run the server with the usual command again. :)

I had to force yarn install, because otherwise it would just be "done" after 1/4 steps... :/ I guess the "done" convinced me too much all that time. :D Or maybe it didn't say 1/4 before? Not sure.

vvv

\* `/usr/lib/node_modules/` is still not recreated. Should that worry me?

**Comment by BrokenEagle** [comment]
> /usr/lib/node_modules/ is still not recreated. Should that worry me?

No, since if the node modules is in the local directory, then at least that repository will work correctly. If you want it to be installed globally, then you would use `yarn global`, but I can't think of any reason to do that unless you need to do something outside of a repository.

Anyways, if your issue is resolved, you can go ahead and close this issue. I'll close it after a day if there's no other response.

**Comment by GlassedSilver** [comment]
Thank you so much for everything! I cannot tell you how happy I am :)
