### ISSUE TITLE
`fav:` search for nonexistent user throws exception

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4352]
https://danbooru.donmai.us/posts?tags=fav%3Ax

```
undefined method `hide_favorites?' for nil:NilClass

    NoMethodError exception raised
    app/logical/post_query_builder.rb:869:in `block in parse_query'
    app/logical/post_query_builder.rb:703:in `each'
    app/logical/post_query_builder.rb:703:in `parse_query'
    app/logical/post_query_builder.rb:159:in `build'
    app/models/post.rb:1547:in `tag_match'
    app/models/post.rb:1098:in `block in fast_count_search'
    app/models/application_record.rb:117:in `with_timeout'
    app/models/post.rb:1097:in `fast_count_search'
    app/models/post.rb:1088:in `fast_count'
    app/logical/post_sets/post.rb:91:in `get_post_count'
    app/logical/post_sets/post.rb:103:in `posts'
    app/controllers/posts_controller.rb:14:in `index'

```

**Comment by evazion** [comment]
Fixed in 2445e8b82.
