### ISSUE TITLE
Artist commentary versions page is broken

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4355]
https://danbooru.donmai.us/artist_commentary_versions

![image](https://user-images.githubusercontent.com/12946050/77485871-92e12100-6e2e-11ea-83bb-f79c9cf80a86.png)

```ruby

ActionView::Template::Error exception raised
app/logical/diff_builder.rb:12:in `build'
app/helpers/application_helper.rb:17:in `diff_body_html'
app/views/artist_commentary_versions/_listing.html.erb:36
app/logical/table_builder.rb:28:in `value'
app/views/table_builder/_table.html.erb:17
app/views/table_builder/_table.html.erb:16
app/views/table_builder/_table.html.erb:15:in `each'
app/views/table_builder/_table.html.erb:15:in `each_with_index'
app/views/table_builder/_table.html.erb:15
app/views/table_builder/_table.html.erb:14
app/views/table_builder/_table.html.erb:13:in `each_with_index'
app/views/table_builder/_table.html.erb:13
app/views/table_builder/_table.html.erb:1
app/helpers/application_helper.rb:240:in `table_for'
app/views/artist_commentary_versions/_listing.html.erb:7
app/views/artist_commentary_versions/index.html.erb:7
app/controllers/application_controller.rb:40:in `respond_with'
app/controllers/artist_commentary_versions_controller.rb:8:in `index'
```

**Comment by BrokenEagle** [comment]
It's the following version which is having issues:

https://danbooru.donmai.us/artist_commentary_versions.xml?search[id]=800406
