### ISSUE TITLE
"unknown keyword: :tag_count" when changing tag category

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4574]
Trying to change the category of [this tag](https://danbooru.donmai.us/posts?tags=princess_freia_%28kotatsu_%28g-rough%29%29) returns the following error: "unknown keyword: :tag_count"
```ruby
ArgumentError exception raised
app/models/tag.rb:170:in `block (2 levels) in update_category_post_counts'
app/models/tag.rb:166:in `block in update_category_post_counts'
app/models/application_record.rb:107:in `with_timeout'
app/models/tag.rb:165:in `update_category_post_counts'
app/models/tag.rb:219:in `find_or_create_by_name'
app/models/post.rb:592:in `block in apply_categorization_metatags'
app/models/post.rb:590:in `map'
app/models/post.rb:590:in `apply_categorization_metatags'
app/models/post.rb:583:in `filter_metatags'
app/models/post.rb:470:in `normalize_tags'
app/controllers/posts_controller.rb:55:in `update'
```

Possibly related to issue #4572.

**Comment by nonamethanks** [comment]
Same error happens when using the edit tag dialog
```

ArgumentError exception raised
app/models/tag.rb:170:in `block (2 levels) in update_category_post_counts'
app/models/tag.rb:166:in `block in update_category_post_counts'
app/models/application_record.rb:107:in `with_timeout'
app/models/tag.rb:165:in `update_category_post_counts'
app/controllers/tags_controller.rb:34:in `update'
```
