### ISSUE TITLE
Broken search for  zip_file status:any

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4576]
A very old post is likely causing issues.
https://danbooru.donmai.us/posts?tags=zip_file+status%3Aany

Error
comparison of NilClass with 850 failed

Details
```ruby

ArgumentError exception raised
app/models/post.rb:241:in `large_image_width'
app/presenters/post_presenter.rb:119:in `data_attributes'
app/presenters/post_presenter.rb:29:in `preview'
app/logical/post_sets/post.rb:144:in `block in post_previews_html'
app/logical/post_sets/post.rb:143:in `post_previews_html'
app/views/posts/partials/index/_posts.html.erb:3
app/views/posts/index.html.erb:39
app/views/posts/index.html.erb:18
app/controllers/application_controller.rb:43:in `respond_with'
app/controllers/posts_controller.rb:15:in `index'
```

**Comment by evazion** [comment]
Fixed in dd44dce5970eda21ae338855bcbba81868ffae56.
