### ISSUE TITLE
Searching for users failed flags fails

### ISSUE THREAD

**Issue by OOZ662** [danbooru/danbooru#4609]
Search a user's flagging history with Status dropdown set to "rejected." Results in the following:

```
Error
'2' is not a valid status

Details
    ArgumentError exception raised
    app/models/post_flag.rb:34:in `creator_matches'
    app/models/post_flag.rb:69:in `search'
    app/models/application_record.rb:20:in `paginated_search'
    app/controllers/post_flags_controller.rb:10:in `index'
```

**Comment by nonamethanks** [comment]
It seems all the status options fail with the same error when searching for an user's flags.
