### ISSUE TITLE
User search by count is broken

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4646]
https://danbooru.donmai.us/users?commit=Search&search%5Border%5D=post_upload_count
https://danbooru.donmai.us/users?commit=Search&search%5Border%5D=name
https://danbooru.donmai.us/users?commit=Search&search%5Border%5D=note_count
All of these are broken for me.

```ruby
No route matches {:action=>"show", :controller=>"ip_addresses", :id=>nil}, possible unmatched constraints: [:id] Did you mean? ip_address_url ip_addresses_url ip_addresses_path

ActionController::UrlGenerationError exception raised
app/views/users/index.html.erb:20
app/logical/table_builder.rb:28:in `value'
app/views/table_builder/_table.html.erb:17
app/views/table_builder/_table.html.erb:16
app/views/table_builder/_table.html.erb:15:in `each'
app/views/table_builder/_table.html.erb:15:in `each_with_index'
app/views/table_builder/_table.html.erb:15
app/views/table_builder/_table.html.erb:14
app/views/table_builder/_table.html.erb:13:in `each_with_index'
app/views/table_builder/_table.html.erb:13
app/views/table_builder/_table.html.erb:1
app/helpers/application_helper.rb:258:in `table_for'
app/views/users/index.html.erb:14
app/controllers/application_controller.rb:44:in `respond_with'
app/controllers/users_controller.rb:38:in `index'
```

**Comment by nonamethanks** [comment]
Fixed by 57e70e5b827e34f22bf65caa0282d85f49a45153.
