### ISSUE TITLE
"Error / That record was not found." after I updated to latest master after half a year of not running the danbooru instance

### ISSUE THREAD

**Issue by GlassedSilver** [danbooru/danbooru#4653]
Latest master on Ubuntu 20.04 LTS (latest updates, correct PostgreSQL version and everything else should be correct to my knowledge)

Here's the run command along with the output from a simple call to view an existing artist.

```
danbooru@ahri-vm-danbooru:~/danbooru$ RUBYOPT=-W0 bundle exec rails server --binding 192.168.2.229
=> Booting Puma
=> Rails 6.1.0 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.1.1 (ruby 2.7.1-p83) ("At Your Service")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 1419
* Listening on http://192.168.2.229:3000
Use Ctrl-C to stop
[PID:1419] Started GET "/artists/746" for 192.168.2.220 at 2021-01-02 23:27:33 +0000
[PID:1419]    (3.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
[PID:1419] Processing by ArtistsController#show as HTML
[PID:1419]   Parameters: {"id"=>"746"}
[PID:1419]   User Load (2.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[PID:1419]   ↳ app/logical/session_loader.rb:85:in `load_session_user'
[PID:1419]    (1.4ms)  set statement_timeout = 60000
[PID:1419]   ↳ app/logical/session_loader.rb:53:in `set_statement_timeout'
[PID:1419]   Artist Load (2.8ms)  SELECT "artists".* FROM "artists" WHERE "artists"."id" = $1 LIMIT $2  [["id", 746], ["LIMIT", 1]]
[PID:1419]   ↳ app/controllers/artists_controller.rb:40:in `show'
[PID:1419]   Rendering layout layouts/default.html.erb
[PID:1419]   Rendering artists/show.html.erb within layouts/default
[PID:1419]   Tag Load (7.6ms)  SELECT "tags".* FROM "tags" WHERE "tags"."name" = $1 LIMIT $2  [["name", "narunaru1320"], ["LIMIT", 1]]
[PID:1419]   ↳ app/views/artists/_secondary_links.html.erb:12
[PID:1419]   Rendered artists/_secondary_links.html.erb (Duration: 98.6ms | Allocations: 48437)
[PID:1419]   WikiPage Load (1.8ms)  SELECT "wiki_pages".* FROM "wiki_pages" WHERE "wiki_pages"."title" = $1 LIMIT $2  [["title", "narunaru1320"], ["LIMIT", 1]]
[PID:1419]   ↳ app/views/artists/_show.html.erb:11
[PID:1419]   Artist Load (1.5ms)  SELECT "artists".* FROM "artists" WHERE "artists"."group_name" = $1  [["group_name", "narunaru1320"]]
[PID:1419]   ↳ app/views/artists/_summary.html.erb:31
[PID:1419]   ArtistUrl Load (1.9ms)  SELECT "artist_urls".* FROM "artist_urls" WHERE "artist_urls"."artist_id" = $1  [["artist_id", 746]]
[PID:1419]   ↳ app/views/artists/_summary.html.erb:39
[PID:1419]   Rendered artists/_summary.html.erb (Duration: 31.1ms | Allocations: 8159)
[PID:1419]   Rendered posts/partials/common/_inline_blacklist.html.erb (Duration: 0.4ms | Allocations: 113)
[PID:1419] Creating scope :active. Overwriting existing method Post.active.
[PID:1419]   User Load (1.4ms)  SELECT "users".* FROM "users" WHERE "users"."name" = $1 LIMIT $2  [["name", "DanbooruBot"], ["LIMIT", 1]]
[PID:1419]   ↳ app/models/user.rb:202:in `system'
[PID:1419]   Rendered artists/_show.html.erb (Duration: 184.8ms | Allocations: 76443)
[PID:1419]   Rendered artists/show.html.erb within layouts/default (Duration: 188.4ms | Allocations: 77050)
[PID:1419]   Rendered layout layouts/default.html.erb (Duration: 190.1ms | Allocations: 77191)
[PID:1419] ActiveRecord::RecordNotFound: Couldn't find User
[PID:1419]   Rendering layout layouts/default.html.erb
[PID:1419]   Rendering static/error.html.erb within layouts/default
[PID:1419]   Rendered static/error.html.erb within layouts/default (Duration: 0.8ms | Allocations: 195)
[PID:1419]   Rendered application/_meta_links.html.erb (Duration: 0.8ms | Allocations: 300)
[PID:1419] [Webpacker] Everything's up-to-date. Nothing to do
[PID:1419]   NewsUpdate Load (2.1ms)  SELECT "news_updates".* FROM "news_updates" WHERE (created_at >= '2020-12-19 23:27:33.707442') ORDER BY created_at desc LIMIT $1  [["LIMIT", 5]]
[PID:1419]   ↳ app/views/news_updates/_listing.html.erb:1
[PID:1419]   Rendered news_updates/_listing.html.erb (Duration: 7.8ms | Allocations: 1698)
[PID:1419]    (1.9ms)  SELECT MAX("forum_topics"."updated_at") FROM "forum_topics" WHERE (min_level <= 50) AND "forum_topics"."is_deleted" = $1  [["is_deleted", false]]
[PID:1419]   ↳ app/models/user.rb:356:in `has_forum_been_updated?'
[PID:1419]   Rendered layouts/_main_links.html.erb (Duration: 26.4ms | Allocations: 7838)
[PID:1419]   Rendered users/_verification_notice.html.erb (Duration: 0.6ms | Allocations: 174)
[PID:1419]   Rendered static/_footer.html.erb (Duration: 1.4ms | Allocations: 506)
[PID:1419]   Rendered layout layouts/default.html.erb (Duration: 58.9ms | Allocations: 17260)
[PID:1419] Completed 404 Not Found in 439ms (Views: 52.9ms | ActiveRecord: 84.5ms | Allocations: 148242)
```

Posts view fine and upload fine.
Trying to create a new wiki page, creating a new artist wiki or viewing either won't work.

Manually adding a new artist (artists > New) and editing (artists > click edit on any artists) both work fine.

Really confused over this behavior. o.O

Any help would be GREATLY appreciated. Happy New Years to everyone btw! :)

**Comment by evazion** [comment]
Try running with: `DANBOORU_DEBUG_MODE=1 RUBYOPT=-W0 bundle exec rails server --binding 192.168.2.229`. This should give you a better error message. The error is the `ActiveRecord::RecordNotFound: Couldn't find User` line, but I'm not sure where that's coming from.

**Comment by GlassedSilver** [comment]
This is in the shell:

```
danbooru@ahri-vm-danbooru:~/danbooru$ DANBOORU_DEBUG_MODE=1 RUBYOPT=-W0 bundle exec rails server --binding 192.168.2.229
=> Booting Puma
=> Rails 6.1.0 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.1.1 (ruby 2.7.1-p83) ("At Your Service")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 11880
* Listening on http://192.168.2.229:3000
Use Ctrl-C to stop
[PID:11880] Started GET "/artists/show_or_new?name=miso-ha_%28ukyuu%29" for 192.168.2.220 at 2021-01-04 06:13:41 +0000
[PID:11880]    (4.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
[PID:11880] Processing by ArtistsController#show_or_new as HTML
[PID:11880]   Parameters: {"name"=>"miso-ha_(ukyuu)"}
[PID:11880]   User Load (10.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[PID:11880]   ↳ app/logical/session_loader.rb:85:in `load_session_user'
[PID:11880]    (3.1ms)  set statement_timeout = 60000
[PID:11880]   ↳ app/logical/session_loader.rb:53:in `set_statement_timeout'
[PID:11880]   Artist Load (2.4ms)  SELECT "artists".* FROM "artists" WHERE "artists"."name" = $1 LIMIT $2  [["name", "miso-ha_(ukyuu)"], ["LIMIT", 1]]
[PID:11880]   ↳ app/controllers/artists_controller.rb:71:in `show_or_new'
[PID:11880] Redirected to http://192.168.2.229:3000/artists/760
[PID:11880] Completed 302 Found in 199ms (ActiveRecord: 40.2ms | Allocations: 53786)


[PID:11880] Started GET "/artists/760" for 192.168.2.220 at 2021-01-04 06:13:41 +0000
[PID:11880] Processing by ArtistsController#show as HTML
[PID:11880]   Parameters: {"id"=>"760"}
[PID:11880]   User Load (1.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[PID:11880]   ↳ app/logical/session_loader.rb:85:in `load_session_user'
[PID:11880]    (1.0ms)  set statement_timeout = 60000
[PID:11880]   ↳ app/logical/session_loader.rb:53:in `set_statement_timeout'
[PID:11880]   Artist Load (1.2ms)  SELECT "artists".* FROM "artists" WHERE "artists"."id" = $1 LIMIT $2  [["id", 760], ["LIMIT", 1]]
[PID:11880]   ↳ app/controllers/artists_controller.rb:40:in `show'
[PID:11880]   Rendering layout layouts/default.html.erb
[PID:11880]   Rendering artists/show.html.erb within layouts/default
[PID:11880]   Tag Load (2.1ms)  SELECT "tags".* FROM "tags" WHERE "tags"."name" = $1 LIMIT $2  [["name", "miso-ha_(ukyuu)"], ["LIMIT", 1]]
[PID:11880]   ↳ app/views/artists/_secondary_links.html.erb:12
[PID:11880]   Rendered artists/_secondary_links.html.erb (Duration: 96.5ms | Allocations: 45082)
[PID:11880]   WikiPage Load (2.1ms)  SELECT "wiki_pages".* FROM "wiki_pages" WHERE "wiki_pages"."title" = $1 LIMIT $2  [["title", "miso-ha_(ukyuu)"], ["LIMIT", 1]]
[PID:11880]   ↳ app/views/artists/_show.html.erb:11
[PID:11880]   Artist Load (1.8ms)  SELECT "artists".* FROM "artists" WHERE "artists"."group_name" = $1  [["group_name", "miso-ha_(ukyuu)"]]
[PID:11880]   ↳ app/views/artists/_summary.html.erb:31
[PID:11880]   ArtistUrl Load (2.1ms)  SELECT "artist_urls".* FROM "artist_urls" WHERE "artist_urls"."artist_id" = $1  [["artist_id", 760]]
[PID:11880]   ↳ app/views/artists/_summary.html.erb:39
[PID:11880]   Rendered artists/_summary.html.erb (Duration: 37.2ms | Allocations: 8511)
[PID:11880]   Rendered posts/partials/common/_inline_blacklist.html.erb (Duration: 0.5ms | Allocations: 113)
[PID:11880] Creating scope :active. Overwriting existing method Post.active.
[PID:11880]   User Load (1.7ms)  SELECT "users".* FROM "users" WHERE "users"."name" = $1 LIMIT $2  [["name", "DanbooruBot"], ["LIMIT", 1]]
[PID:11880]   ↳ app/models/user.rb:202:in `system'
[PID:11880]   Rendered artists/_show.html.erb (Duration: 196.7ms | Allocations: 72366)
[PID:11880]   Rendered artists/show.html.erb within layouts/default (Duration: 198.7ms | Allocations: 72810)
[PID:11880]   Rendered layout layouts/default.html.erb (Duration: 199.2ms | Allocations: 72883)
[PID:11880] Completed 500 Internal Server Error in 219ms (ActiveRecord: 34.1ms | Allocations: 77088)


[PID:11880]
[PID:11880] ActionView::Template::Error (Couldn't find User):
[PID:11880]     27:           <%= render "posts/partials/common/inline_blacklist" %>
[PID:11880]     28:
[PID:11880]     29:           <div>
[PID:11880]     30:             <%= post_previews_html(@artist.tag.posts.limit(8), tags: @artist.name) %>
[PID:11880]     31:           </div>
[PID:11880]     32:         </div>
[PID:11880]     33:       <% end %>
[PID:11880]
[PID:11880] app/models/user.rb:202:in `system'
[PID:11880] app/models/post.rb:1284:in `system_tag_match'
[PID:11880] app/models/tag.rb:353:in `posts'
[PID:11880] app/views/artists/_show.html.erb:30
[PID:11880] app/views/artists/show.html.erb:1
[PID:11880] app/controllers/application_controller.rb:44:in `respond_with'
[PID:11880] app/controllers/artists_controller.rb:41:in `show'
```

**Comment by evazion** [comment]
Looks like the `DanbooruBot` account doesn't exist. Run `bin/rails db:seed` to create it. Or you can edit `config/danbooru_default_config.rb` and change `system_user` to the name of some other user.

**Comment by GlassedSilver** [comment]
Thank you so much, that fixed it! :)
