### ISSUE TITLE
Hentai-Foundry: Document tree depth limit exceeded

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4657]
Some Hentai-Foundry sources fail to upload. http://www.hentai-foundry.com/pictures/user/LumiNyu/867562/Mona-patreon-winner:

```
Document tree depth limit exceeded 
/var/www/danbooru/releases/20210101103615/app/logical/danbooru/http/html_adapter.rb:8:in `decode' 
/var/www/danbooru/releases/20210101103615/app/logical/sources/strategies/hentai_foundry.rb:70:in `page' 
/var/www/danbooru/releases/20210101103615/app/logical/sources/strategies/hentai_foundry.rb:41:in `image_urls' 
/var/www/danbooru/releases/20210101103615/app/logical/sources/strategies/base.rb:77:in `image_url' 
/var/www/danbooru/releases/20210101103615/app/logical/sources/strategies/hentai_foundry.rb:86:in `canonical_url' 
/var/www/danbooru/releases/20210101103615/app/logical/upload_service/preprocessor.rb:31:in `canonical_source' 
/var/www/danbooru/releases/20210101103615/app/logical/upload_service/preprocessor.rb:70:in `start!' 
/var/www/danbooru/releases/20210101103615/app/logical/upload_service/preprocessor.rb:61:in `block in delayed_start' 
/var/www/danbooru/releases/20210101103615/app/logical/current_user.rb:10:in `scoped' 
/var/www/danbooru/releases/20210101103615/app/logical/current_user.rb:24:in `as' 
/var/www/danbooru/releases/20210101103615/app/logical/upload_service/preprocessor.rb:60:in `delayed_start' 
/var/www/danbooru/releases/20210101103615/app/jobs/upload_preprocessor_delayed_start_job.rb:6:in `perform'
--
```

Caused by extremely deeply nested HTML tags in commentaries (see also https://github.com/danbooru/danbooru/issues/4477#issuecomment-632319234).

**Comment by lllusion3469** [comment]
It's only somewhat related: This seems to only be a problem with Nokogumbo's `Nokogiri::HTML5` class. [It's also possible to override or disable the limit](https://github.com/rubys/nokogumbo#user-content-maximum-tree-depth) via the `max_tree_depth` parameter (`-1` disables it).
