### ISSUE TITLE
Regarding IQDB: How to configure it in Danbooru?

### ISSUE THREAD

**Issue by GlassedSilver** [danbooru/danbooru#4866]
Hey, maybe this is a silly question and I'm not seeing something obvious, been trying to get this to work for a while now, but to no avail.

I have Danbooru running within a VM (but not within a docker), however my IQDB instance sits in a docker in the same VM.

I'm trying to link them up, but if I configure IQDB in my `danbooru_local_config.rb` like so:

```
    def iqdb_url
      "http://localhost:5588/iqdb"
    end
```

the IQDB response status is not 200 and hence caught by a page titled: 

> HTTP::Error at /iqdb_queries
> 
> Unknown MIME type:
>
> [etc ...]

Bit unsure how to proceed.

**Comment by evazion** [comment]
Two things:

* Use `http://localhost:5588` not `http://localhost:5588/iqdb` as your IQDB url. `http://localhost:5588/iqdb` won't work unless you have something like Nginx set up to run iqdb under a subdirectory.
* Make sure port 5588 is exposed by Docker.

You can run IQDB something like:

```
docker run --rm -it -p 5588:5588 -v /home/danbooru/iqdb:/mnt evazion/iqdb http 0.0.0.0 5588 /mnt/iqdb.sqlite
```

where:

* `--rm -it` means run in the foreground and delete the container when it's done. Replace this with `-d` to run as a daemon in the background.
* `-p 5588:5588` means expose the port 5588 inside Docker as port 5588 outside of Docker.
* `-v /home/danbooru/iqdb:/mnt` means mount the directory `/home/danbooru/iqdb` outside of Docker as the directory `/mnt` inside of Docker. `/home/danbooru/iqdb` is where the IQDB database will be stored on the host system. You can change this to anywhere.
* `/mnt/iqdb.sqlite` is the database filename inside Docker. You can change `iqdb.sqlite` to anything.

You can test IQDB is working with `curl -v http://localhost:5588/status` or `curl -F file=@test.jpg 'http://localhost:5588/query` where `test.jpg` is any test image.

**Comment by GlassedSilver** [comment]
MAN... I just.... I just love you, okay. Thank you so much. I was simply going off of the docker-compose file here and didn't notice that 5588 wasn't even being exposed. I mean, kinda logical, since normally in a fully dockerized environment you don't need to expose 5588 since it just stays within the same virtual host of the docker stack.

Really you saved my night. One last question then, I noticed from reading the README over at danbooru/iqdb that there's two modes to operate IQDB in, one is maintanence which is write and read and then query, which I presume is what is used by danbooru to query the instance.

My question is: how do I push all of my database that's in danbooru already into IQDB at once and how to maintain it?

I'm sorry for needing the dogfeeding here again. o(￣┰￣*)ゞ

**Comment by evazion** [comment]
That README was outdated. I've rewritten it.

IQDB is safe to shut down with ctrl+c. Before images would only be saved to disk on a clean exit; now they're saved as soon as they're added to IQDB.

You can run `bin/rails danbooru:reindex_posts` to put all existing posts in IQDB. You need to make sure the delayed job worker is running (`bin/delayed_job run`) because posts will be put into IQDB as a background job.

The recommender server hasn't been Dockerized yet so running it will involve installing everything manually and praying it works. Also make sure you're using the one at https://github.com/evazion/recommender not https://github.com/r8888888888/recommender.

**Comment by GlassedSilver** [comment]
Ah, wonderful, thank you for helping me so much here. I really cannot express how grateful I am.

Ah that's cool that it's safe to interrrupt it now as well!

delayed_job worker is running (at least I think.... I get messages similar to this one a lot in that screen session that I inspect as I try out IQDB):

`  Delayed::Backend::ActiveRecord::Job Load (1.4ms)  UPDATE "delayed_jobs" SET locked_at = '2021-08-29 11:35:11.411656', locked_by = 'delayed_job host:ahri-vm-danbooru.local pid:33479' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE (((run_at <= '2021-08-29 11:35:11.409473' AND (locked_at IS NULL OR locked_at < '2021-08-29 07:35:11.409501')) OR locked_by = 'delayed_job host:ahri-vm-danbooru.local pid:33479') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *`

When I then run `bin/rails danbooru:reindex_posts` from `~/danbooru/` (so same workdir as for the command above if I'm not mistaken) I get this:
```
  Delayed::Backend::ActiveRecord::Job Load (1.5ms)  UPDATE "delayed_jobs" SET locked_at = '2021-08-29 11:30:04.507081', locked_by = 'delayed_job host:ahri-vm-danbooru.local pid:33430' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE (((run_at <= '2021-08-29 11:30:04.505218' AND (locked_at IS NULL OR locked_at < '2021-08-29 07:30:04.505246')) OR locked_by = 'delayed_job host:ahri-vm-danbooru.local pid:33430') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
  Delayed::Backend::ActiveRecord::Job Load (1.3ms)  UPDATE "delayed_jobs" SET locked_at = '2021-08-29 11:30:09.914376', locked_by = 'delayed_job host:ahri-vm-danbooru.local pid:33430' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE (((run_at <= '2021-08-29 11:30:09.912649' AND (locked_at IS NULL OR locked_at < '2021-08-29 07:30:09.912675')) OR locked_by = 'delayed_job host:ahri-vm-danbooru.local pid:33430') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
^CI, [2021-08-29T13:30:14.807128 #33430]  INFO -- : 2021-08-29T13:30:14+0200: [Worker(delayed_job host:ahri-vm-danbooru.local pid:33430)] Exiting...
  Delayed::Backend::ActiveRecord::Job Update All (0.7ms)  UPDATE "delayed_jobs" SET "locked_by" = $1, "locked_at" = $2 WHERE "delayed_jobs"."locked_by" = $3  [["locked_by", nil], ["locked_at", nil], ["locked_by", "delayed_job host:ahri-vm-danbooru.local pid:33430"]]
danbooru@ahri-vm-danbooru:~/danbooru$ bin/rails danbooru:reindex_posts
rails aborted!
Don't know how to build task 'danbooru:reindex_posts' (See the list of available tasks with `rails --tasks`)
Did you mean?  danbooru:cron

(See full trace by running task with --trace)
danbooru@ahri-vm-danbooru:~/danbooru$
```

(I shortened that output to the last bit I get before getting thrown out.)

As for the recommender, yeah I'm not sure my sleepiness is gonna help here, maybe I'll revisit that module later on, right now my browser already has dozens of tabs open from researching some errors, fixing dependencies, etc... :D
(I bet you know what I mean, doesn't help that I have well over 1000 tabs open in a few windows of pixiv pages and stuff that I wanna still add to my instance. Oh Lord :P)

**Comment by evazion** [comment]
I misspoke, I meant to say `bin/rails danbooru:reindex_iqdb`.

**Comment by GlassedSilver** [comment]
Still get an error. :/

```
danbooru@ahri-vm-danbooru:~/danbooru$ bin/rails danbooru:reindex_iqdb --trace                                                       rails aborted!
Don't know how to build task 'danbooru:reindex_iqdb' (See the list of available tasks with `rails --tasks`)                         Did you mean?  danbooru:cron
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task_manager.rb:59:in `[]'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:159:in `invoke_task'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/command.rb:52:in `invoke'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails/commands.rb:18:in `<main>'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/danbooru/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
```

Putting on my detective cap I get this:

```
danbooru@ahri-vm-danbooru:~/danbooru$ bin/rails --tasks
rails about                              # List versions of a...
rails app:template                       # Applies the templa...
rails app:update                         # Update configs and...
rails cache_digests:dependencies         # Lookup first-level...
rails cache_digests:nested_dependencies  # Lookup nested depe...
rails danbooru:cron                      # Run the cronjob sc...
rails danbooru:docker:build              # Build a Docker ima...
rails db:create                          # Creates the databa...
rails db:drop                            # Drops the database...
rails db:environment:set                 # Set the environmen...
rails db:fixtures:load                   # Loads fixtures int...
rails db:migrate                         # Migrate the databa...
rails db:migrate:down                    # Runs the "down" fo...
rails db:migrate:redo                    # Rolls back the dat...
rails db:migrate:status                  # Display status of ...
rails db:migrate:up                      # Runs the "up" for ...
rails db:prepare                         # Runs setup if data...
rails db:reset                           # Drops and recreate...
rails db:rollback                        # Rolls the schema b...
rails db:schema:cache:clear              # Clears a db/schema...
rails db:schema:cache:dump               # Creates a db/schem...
rails db:schema:dump                     # Creates a database...
rails db:schema:load                     # Loads a database s...
rails db:seed                            # Loads the seed dat...
rails db:seed:replant                    # Truncates tables o...
rails db:setup                           # Creates the databa...
rails db:structure:dump                  # Dumps the database...
rails db:structure:load                  # Recreates the data...
rails db:version                         # Retrieves the curr...
rails images:backup                      # Backup images
rails images:regen                       # Regenerate thumbna...
rails jobs:check[max_age]                # Exit with error st...
rails jobs:clear                         # Clear the delayed_...
rails jobs:work                          # Start a delayed_jo...
rails jobs:workoff                       # Start a delayed_jo...
rails log:clear                          # Truncates all/spec...
rails maintenance:daily                  # Run daily maintena...
rails maintenance:hourly                 # Run hourly mainten...
rails maintenance:monthly                # Run monthly mainte...
rails maintenance:weekly                 # Run weekly mainten...
rails middleware                         # Prints out your Ra...
rails restart                            # Restart app by tou...
rails secret                             # Generate a cryptog...
rails stats                              # Report code statis...
rails test                               # Runs all tests in ...
rails test:all                           # Runs all tests, in...
rails test:db                            # Run tests quickly,...
rails test:system                        # Run system tests only
rails time:zones[country_or_offset]      # List all time zone...
rails tmp:clear                          # Clear cache, socke...
rails tmp:create                         # Creates tmp direct...
rails webpacker                          # Lists all availabl...
rails webpacker:binstubs                 # Installs Webpacker...
rails webpacker:check_binstubs           # Verifies that bin/...
rails webpacker:check_node               # Verifies if Node.j...
rails webpacker:check_yarn               # Verifies if Yarn i...
rails webpacker:clean[keep,age]          # Remove old compile...
rails webpacker:clobber                  # Remove the webpack...
rails webpacker:compile                  # Compile JavaScript...
rails webpacker:info                     # Provide informatio...
rails webpacker:install                  # Install Webpacker ...
rails webpacker:verify_install           # Verifies if Webpac...
rails webpacker:yarn_install             # Support for older ...
rails yarn:install                       # Install all JavaSc...
rails zeitwerk:check                     # Checks project str...
```

**Comment by nonamethanks** [comment]
Dumb question, did you pull the master branch recently? Because `danbooru:reindex_iqdb` was added in https://github.com/danbooru/danbooru/commit/d7cc844bd95b7ca2de76a3bd68ef35e63a7b5e94.

**Comment by GlassedSilver** [comment]
> 
> 
> Dumb question, did you pull the master branch recently? Because `danbooru:reindex_iqdb` was added in [d7cc844](https://github.com/danbooru/danbooru/commit/d7cc844bd95b7ca2de76a3bd68ef35e63a7b5e94).

Hah, excellent catch! Thank you so much! My instance is updating as we speak. :P

**Comment by GlassedSilver** [comment]
Can I flush the queue somehow? I think that I may have messed up the delayed_job queue when I restarted danbooru and/or IQDB in my testing with it.

I think I got impatient with it. Would be cool to restart the queue and then watch `~/danbooru/iqdb/iqdb.sqlite` for changes before I do any messing around with restarting services. :D

**Comment by evazion** [comment]
You can go to https://danbooru.donmai.us/delayed_jobs on your instance to view the job queue then use the Cancel / Delete buttons to stop jobs individually. Or you can run `bin/rails dbconsole` then do `DELETE FROM delayed_jobs WHERE handler ~ 'Iqdb';` to delete all IQDB jobs, or `DELETE FROM delayed_jobs;` to delete all jobs entirely (proceed with caution).

You should be able to see the IQDB logs with `docker logs --follow 5b13` where 5b13 is IQDB's container ID (use `docker ps` to find it). You will see log messages if IQDB is adding images.

**Comment by GlassedSilver** [comment]
Okay, well I did wipe the iqdb docker instance and started anew.

I also did issue the first command (`DELETE FROM delayed_jobs WHERE handler ~ 'Iqdb';`) in the `bin/rails dbconsol`e, however:

the https://danbooru.donmai.us/delayed_jobs page (yes, for my URL) is empty and lists nothing (on editing this comment, maybe it has something to do with the job date and time cutoff and they will populate once delayed_job works itself forward?). Getting back into the screen session that I started it in (I leave it running in a detached screen, just like how I keep danbooru itself up. Big fan of `screen`, what a lovely tool!) shows that activity seems pretty low (just checks for jobs if I can tell correctly), no issuing of iqdb additions as far as I can see after an initial round of additions.

I wonder what pacing is expected to be like? Maybe I should systemd launch delayed_job instead, but it's not like delayed_job isn't running.

Could it be that it fires off a bunch of tasks and then waits to add any further with a "cooldown" of 2h?

If my understanding is correct, the delayed_job service is checking what's in the queue by referencing jobs by their date and time, possibly upping or downing the speed depending on how long the queries take. If I'm not wrong, the service will pick up most of the work in about 2h's time after issuing the reindex command. (roughly)

This is the first time I actually get some hands-on experience with load-balancing, so forgive me if I'm not getting something pretty basic and patience would be in order. I try to be, just that at the same time I have a drive to understand more about danbooru works as well.

At first I started off with a light interest in how danbooru works, but I wanted a setup that's easy. Given how mighty it is, I really got welcomed warmly here and a little later I can now happily report that I'm sitting at over 2000 manually curated items in my danbooru instance, but something I gained as well is a fascination with the project and how it works internally.

My understanding of every intricacy is still very limited, but I've already learned so much from all of this. I am forever grateful for all the support I've gotten so far and the opportunity to learn about the workings of a site that is on the scale of danbooru.
