### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by MarioCraftLP** [danbooru/danbooru#5169]
Hi, i am not very good with this but i made everything exactly like in the "Ubuntu Installation Help Guide" and when i start the server and enter the local website, i get this error: 
        [GoodJob] Notifier errored: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
And here is a picture of what the website looks like:
![grafik](https://user-images.githubusercontent.com/75859777/168446048-6245a9c9-1a50-405c-af73-3758d3e64762.png)

**Comment by nottalulah** [comment]
You need postgresql running on your local machine.

**Comment by MarioCraftLP** [comment]
I have postgresql-12 because it says "Unable to locate package postgresql-11", is that the problem?

**Comment by nottalulah** [comment]
That wouldn't give you the error you get. Make sure you've started the server. If you use systemd, run `sudo systemctl start postgresql.service`.

**Comment by MarioCraftLP** [comment]
I tried it, but it is still the same error

**Comment by nottalulah** [comment]
Did it fail to start for some reason? Check the logs with `systemctl status postgresql`.

**Comment by MarioCraftLP** [comment]
danbooru@ubuntu:~/danbooru$ systemctl status postgresql
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
     Active: active (exited) since Sat 2022-05-14 19:55:43 UTC; 4min 51s ago
    Process: 686 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 686 (code=exited, status=0/SUCCESS)

Warning: some journal files were not opened due to insufficient permissions.


when i start there is this big notification
```
 ["/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.                                               0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in                                                new_client'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ac                                               tiverecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:77:                                               in `new_client'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems                                               /activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:                                               37:in `postgresql_connection'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/g                                               ems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract                                               /connection_pool.rb:656:in `public_send'", "/home/danbooru/.rbenv/versions/3.1.2                                               /lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapte                                               rs/abstract/connection_pool.rb:656:in `new_connection'", "/home/danbooru/.rbenv/                                               versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/con                                               nection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'",                                                "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.                                               3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_                                               to_checkout_new_connection'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gem                                               s/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/c                                               onnection_pool.rb:640:in `acquire_connection'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_a                                               dapters/abstract/connection_pool.rb:341:in `checkout'", "/home/danbooru/.rbenv/v                                               ersions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/conn                                               ection_adapters/abstract/connection_pool.rb:181:in `connection'", "/home/danboor                                               u/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_r                                               ecord/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connec                                               tion'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerec                                               ord-7.0.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'"                                               , "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.                                               0.3/lib/active_record/connection_handling.rb:280:in `connection'", "/home/danboo                                               ru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_                                               record/model_schema.rb:568:in `load_schema!'", "/home/danbooru/.rbenv/versions/3                                               .1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/attributes.rb                                               :264:in `load_schema!'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1                                               .0/gems/activerecord-7.0.3/lib/active_record/encryption/encryptable_record.rb:12                                               2:in `load_schema!'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/                                               gems/activerecord-7.0.3/lib/active_record/model_schema.rb:554:in `block in load_                                               schema'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activer                                               ecord-7.0.3/lib/active_record/model_schema.rb:551:in `synchronize'", "/home/danb                                               ooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/activ                                               e_record/model_schema.rb:551:in `load_schema'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/model_schema                                               .rb:417:in `attribute_types'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/ge                                               ms/3.1.0/gems/activerecord-7.0.3/lib/active_record/model_schema.rb:443:in `type_                                               for_attribute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/                                               activerecord-7.0.3/lib/active_record/type_caster/map.rb:16:in `type_for_attribut                                               e'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord                                               -7.0.3/lib/arel/table.rb:107:in `type_for_attribute'", "/home/danbooru/.rbenv/ve                                               rsions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/table                                               _metadata.rb:18:in `type'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/                                               3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/predicate_builder.rb:59                                               :in `build'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/act                                               iverecord-7.0.3/lib/active_record/relation/predicate_builder.rb:54:in `[]'", "/h                                               ome/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/l                                               ib/active_record/relation/predicate_builder.rb:126:in `block in expand_from_hash                                               '", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-                                               7.0.3/lib/active_record/relation/predicate_builder.rb:79:in `each'", "/home/danb                                               ooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/activ                                               e_record/relation/predicate_builder.rb:79:in `flat_map'", "/home/danbooru/.rbenv                                               /versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/re                                               lation/predicate_builder.rb:79:in `expand_from_hash'", "/home/danbooru/.rbenv/ve                                               rsions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relat                                               ion/predicate_builder.rb:25:in `build_from_hash'", "/home/danbooru/.rbenv/versio                                               ns/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/                                               query_methods.rb:1299:in `build_where_clause'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/que                                               ry_methods.rb:742:in `where!'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/g                                               ems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/query_methods.rb:73                                               7:in `where'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/go                                               od_job-2.14.2/lib/good_job/execution.rb:76:in `block in <class:Execution>'", "/h                                               ome/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/l                                               ib/active_record/relation.rb:435:in `instance_exec'", "/home/danbooru/.rbenv/ver                                               sions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relati                                               on.rb:435:in `block in _exec_scope'", "/home/danbooru/.rbenv/versions/3.1.2/lib/                                               ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:880:in `_s                                               coping'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activer                                               ecord-7.0.3/lib/active_record/relation.rb:435:in `_exec_scope'", "/home/danbooru                                               /.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_re                                               cord/scoping/named.rb:175:in `block in scope'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/good_job-2.14.2/lib/good_job/execution.rb:157:in                                                `perform_with_advisory_lock'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/ge                                               ms/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:108:in                                                `public_send'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/                                               activerecord-7.0.3/lib/active_record/relation/delegation.rb:108:in `block in met                                               hod_missing'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ac                                               tiverecord-7.0.3/lib/active_record/relation.rb:880:in `_scoping'", "/home/danboo                                               ru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_                                               record/relation.rb:428:in `scoping'", "/home/danbooru/.rbenv/versions/3.1.2/lib/                                               ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb                                               :108:in `method_missing'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3                                               .1.0/gems/good_job-2.14.2/lib/good_job/job_performer.rb:27:in `next'", "/home/da                                               nbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-2.14.2/lib/good_j                                               ob/scheduler.rb:270:in `block (2 levels) in create_task'", "/home/danbooru/.rben                                               v/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support                                               /execution_wrapper.rb:92:in `wrap'", "/home/danbooru/.rbenv/versions/3.1.2/lib/r                                               uby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/reloader.rb:72:in `bl                                               ock in wrap'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ac                                               tivesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'", "/home/                                               danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/                                               active_support/reloader.rb:71:in `wrap'", "/home/danbooru/.rbenv/versions/3.1.2/                                               lib/ruby/gems/3.1.0/gems/good_job-2.14.2/lib/good_job/scheduler.rb:269:in `block                                                in create_task'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gem                                               s/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_execu                                               tor.rb:24:in `block in execute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby                                               /gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchroni                                               zation/mutex_lockable_object.rb:47:in `block in synchronize'", "/home/danbooru/.                                               rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurr                                               ent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'                                               ", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-rub                                               y-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb                                               :47:in `synchronize'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0                                               /gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_e                                               xecutor.rb:22:in `execute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems                                               /3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/ivar.rb:169:in                                                `safe_execute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems                                               /concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in                                                `process_task'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/                                               concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:i                                               n `block in ns_post_task'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/                                               3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_t                                               hread_pool_executor.rb:352:in `run_task'", "/home/danbooru/.rbenv/versions/3.1.2                                               /lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/                                               executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'                                               ", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-rub                                               y-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:33                                               4:in `loop'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/con                                               current-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_exe                                               cutor.rb:334:in `block (2 levels) in create_worker'", "/home/danbooru/.rbenv/ver                                               sions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/                                               concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'", "/home/danboor                                               u/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/conc                                               urrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in cr                                               eate_worker'"]
[GoodJob] GoodJob error: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?

 ["/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.                                               0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in                                                new_client'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ac                                               tiverecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:77:                                               in `new_client'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems                                               /activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:                                               37:in `postgresql_connection'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/g                                               ems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract                                               /connection_pool.rb:656:in `public_send'", "/home/danbooru/.rbenv/versions/3.1.2                                               /lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapte                                               rs/abstract/connection_pool.rb:656:in `new_connection'", "/home/danbooru/.rbenv/                                               versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/con                                               nection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'",                                                "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.                                               3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_                                               to_checkout_new_connection'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gem                                               s/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/c                                               onnection_pool.rb:640:in `acquire_connection'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_a                                               dapters/abstract/connection_pool.rb:341:in `checkout'", "/home/danbooru/.rbenv/v                                               ersions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/conn                                               ection_adapters/abstract/connection_pool.rb:181:in `connection'", "/home/danboor                                               u/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_r                                               ecord/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connec                                               tion'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerec                                               ord-7.0.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'"                                               , "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.                                               0.3/lib/active_record/connection_handling.rb:280:in `connection'", "/home/danboo                                               ru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_                                               record/model_schema.rb:568:in `load_schema!'", "/home/danbooru/.rbenv/versions/3                                               .1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/attributes.rb                                               :264:in `load_schema!'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1                                               .0/gems/activerecord-7.0.3/lib/active_record/encryption/encryptable_record.rb:12                                               2:in `load_schema!'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/                                               gems/activerecord-7.0.3/lib/active_record/model_schema.rb:554:in `block in load_                                               schema'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activer                                               ecord-7.0.3/lib/active_record/model_schema.rb:551:in `synchronize'", "/home/danb                                               ooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/activ                                               e_record/model_schema.rb:551:in `load_schema'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/model_schema                                               .rb:417:in `attribute_types'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/ge                                               ms/3.1.0/gems/activerecord-7.0.3/lib/active_record/model_schema.rb:443:in `type_                                               for_attribute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/                                               activerecord-7.0.3/lib/active_record/type_caster/map.rb:16:in `type_for_attribut                                               e'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord                                               -7.0.3/lib/arel/table.rb:107:in `type_for_attribute'", "/home/danbooru/.rbenv/ve                                               rsions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/table                                               _metadata.rb:18:in `type'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/                                               3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/predicate_builder.rb:59                                               :in `build'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/act                                               iverecord-7.0.3/lib/active_record/relation/predicate_builder.rb:54:in `[]'", "/h                                               ome/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/l                                               ib/active_record/relation/predicate_builder.rb:126:in `block in expand_from_hash                                               '", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-                                               7.0.3/lib/active_record/relation/predicate_builder.rb:79:in `each'", "/home/danb                                               ooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/activ                                               e_record/relation/predicate_builder.rb:79:in `flat_map'", "/home/danbooru/.rbenv                                               /versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/re                                               lation/predicate_builder.rb:79:in `expand_from_hash'", "/home/danbooru/.rbenv/ve                                               rsions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relat                                               ion/predicate_builder.rb:25:in `build_from_hash'", "/home/danbooru/.rbenv/versio                                               ns/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/                                               query_methods.rb:1299:in `build_where_clause'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/que                                               ry_methods.rb:742:in `where!'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/g                                               ems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/query_methods.rb:73                                               7:in `where'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/go                                               od_job-2.14.2/lib/good_job/execution.rb:76:in `block in <class:Execution>'", "/h                                               ome/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/l                                               ib/active_record/relation.rb:435:in `instance_exec'", "/home/danbooru/.rbenv/ver                                               sions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relati                                               on.rb:435:in `block in _exec_scope'", "/home/danbooru/.rbenv/versions/3.1.2/lib/                                               ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:880:in `_s                                               coping'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activer                                               ecord-7.0.3/lib/active_record/relation.rb:435:in `_exec_scope'", "/home/danbooru                                               /.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_re                                               cord/scoping/named.rb:175:in `block in scope'", "/home/danbooru/.rbenv/versions/                                               3.1.2/lib/ruby/gems/3.1.0/gems/good_job-2.14.2/lib/good_job/execution.rb:157:in                                                `perform_with_advisory_lock'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/ge                                               ms/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:108:in                                                `public_send'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/                                               activerecord-7.0.3/lib/active_record/relation/delegation.rb:108:in `block in met                                               hod_missing'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ac                                               tiverecord-7.0.3/lib/active_record/relation.rb:880:in `_scoping'", "/home/danboo                                               ru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_                                               record/relation.rb:428:in `scoping'", "/home/danbooru/.rbenv/versions/3.1.2/lib/                                               ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb                                               :108:in `method_missing'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3                                               .1.0/gems/good_job-2.14.2/lib/good_job/job_performer.rb:27:in `next'", "/home/da                                               nbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-2.14.2/lib/good_j                                               ob/scheduler.rb:270:in `block (2 levels) in create_task'", "/home/danbooru/.rben                                               v/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support                                               /execution_wrapper.rb:92:in `wrap'", "/home/danbooru/.rbenv/versions/3.1.2/lib/r                                               uby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/reloader.rb:72:in `bl                                               ock in wrap'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ac                                               tivesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'", "/home/                                               danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/                                               active_support/reloader.rb:71:in `wrap'", "/home/danbooru/.rbenv/versions/3.1.2/                                               lib/ruby/gems/3.1.0/gems/good_job-2.14.2/lib/good_job/scheduler.rb:269:in `block                                                in create_task'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gem                                               s/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_execu                                               tor.rb:24:in `block in execute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby                                               /gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchroni                                               zation/mutex_lockable_object.rb:47:in `block in synchronize'", "/home/danbooru/.                                               rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurr                                               ent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'                                               ", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-rub                                               y-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb                                               :47:in `synchronize'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0                                               /gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_e                                               xecutor.rb:22:in `execute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems                                               /3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/ivar.rb:169:in                                                `safe_execute'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems                                               /concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in                                                `process_task'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/                                               concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:i                                               n `block in ns_post_task'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/                                               3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_t                                               hread_pool_executor.rb:352:in `run_task'", "/home/danbooru/.rbenv/versions/3.1.2                                               /lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/                                               executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'                                               ", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-rub                                               y-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:33                                               4:in `loop'", "/home/danbooru/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/con                                               current-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_exe                                               cutor.rb:334:in `block (2 levels) in create_worker'", "/home/danbooru/.rbenv/ver                                               sions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/                                               concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'", "/home/danboor                                               u/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/conc                                               urrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in cr                                               eate_worker'"]
[PID:5275] Started POST "/__better_errors/11438d31f935febb/variables" for 192.16                                               8.2.109 at 2022-05-14 19:58:12 +0000
[PID:5275] Started POST "/__better_errors/11438d31f935febb/variables" for 192.16                                               8.2.109 at 2022-05-14 19:58:12 +0000
Since there is no EDITOR or BETTER_ERRORS_EDITOR environment variable, using Tex                                               tmate by default.

```

**Comment by nottalulah** [comment]
Oh, apparently the service file on Ubuntu should be something like `postgresql@12-main.service` instead, so try starting that I guess.

**Comment by MarioCraftLP** [comment]
``` danbooru@ubuntu:~$ sudo systemctl start postgresql@12-main.service
Assertion failed on job for postgresql@12-main.service.
```

**Comment by nottalulah** [comment]
You'll have to show logs (just replace `start` with `status` in the last command).

**Comment by MarioCraftLP** [comment]
```
danbooru@ubuntu:~$ sudo systemctl status postgresql@12-main.service
● postgresql@12-main.service - PostgreSQL Cluster 12-main
     Loaded: loaded (/lib/systemd/system/postgresql@.service; disabled; vendor preset: enabled)
     Active: inactive (dead)

May 14 20:32:14 ubuntu systemd[1]: postgresql@12-main.service: Starting requested but asserts failed.
May 14 20:32:14 ubuntu systemd[1]: Assertion failed for PostgreSQL Cluster 12-main.
May 14 20:32:22 ubuntu systemd[1]: postgresql@12-main.service: Starting requested but asserts failed.
May 14 20:32:22 ubuntu systemd[1]: Assertion failed for PostgreSQL Cluster 12-main.
```

**Comment by MarioCraftLP** [comment]
so, i did it with the quick start and no it works, so it is fixed I guess?
