### ISSUE TITLE
NoMethodError on Jobs Index

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#5236]
## Error
`Unexpected error: NoMethodError.`

### Details
```
NoMethodError exception raised
app/views/jobs/index.html.erb:14
app/logical/table_builder.rb:66:in `value'
app/views/table_builder/_table.html.erb:17
app/views/table_builder/_table.html.erb:16
app/views/table_builder/_table.html.erb:15:in `each'
app/views/table_builder/_table.html.erb:15:in `each_with_index'
app/views/table_builder/_table.html.erb:15
app/views/table_builder/_table.html.erb:14
app/views/table_builder/_table.html.erb:13:in `each_with_index'
app/views/table_builder/_table.html.erb:13
app/views/table_builder/_table.html.erb:1
app/helpers/application_helper.rb:278:in `table_for'
app/views/jobs/index.html.erb:12
app/controllers/application_controller.rb:64:in `respond_with'
app/controllers/jobs_controller.rb:8:in `index'
```

https://github.com/danbooru/danbooru/blob/9000fa63b/app/views/jobs/index.html.erb#L13-L15

I assume that the job class is null, but I can't tell because the JSON doesn't show the job class.

**Comment by nonamethanks** [comment]
@BrokenEagle is this the same issue as #5229, already fixed in betabooru?

**Comment by BrokenEagle** [comment]
Seems to be.... ugh... I even searched if there had been any opened/closed issues first before making this one. T_T
