### ISSUE TITLE
tag_aliases - wrong results with paginate_sequential_after

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#5262]
go to
<https://danbooru.donmai.us/tag_aliases.json?page=a14526&only=id&limit=1000>
item # 605 has an `id` completely outside the `>14526` range:
```js
...
{"id": 15028},
{"id": 4120},
{"id": 15027},
...
```
also note that the results aren't properly ordered, and some ids in the 44XXX range appear to be randomly mixed-in as well.

in a fresh (dev) environment i couldn't find a reason for this and couldn't reproduce it,
the request produced these logs:
```
[PID:18478] Started GET "//tag_aliases.json?page=a14526&only=id&limit=1000" for 10.0.2.2 at 2022-09-25 19:12:52 +1000
[PID:18478] Processing by TagAliasesController#index as JSON
[PID:18478]   Parameters: {"page"=>"a14526", "only"=>"id", "limit"=>"1000"}
[PID:18478]    (0.5ms)  set statement_timeout = 60000
[PID:18478]   ↳ app/logical/session_loader.rb:100:in `set_statement_timeout'
[PID:18478]   TagAlias Load (1.7ms)  SELECT "tag_aliases".* FROM "tag_aliases" WHERE (tag_aliases.id > '14526') ORDER BY tag_aliases.id ASC LIMIT $1  [["LIMIT", 1001]]
[PID:18478]   ↳ app/logical/pagination_extension.rb:139:in `records'
[PID:18478] Completed 200 OK in 7ms (Views: 1.4ms | ActiveRecord: 2.2ms | Allocations: 4281)
```
so if the same query is being executed in production i'm not sure how id 4120 could slip through the `(tag_aliases.id > '14526')` condition.

i tried manually creating an alias with that id:
```sql
insert into tag_aliases
(id, antecedent_name, consequent_name, creator_id, created_at, updated_at)
values
(4120, 'a', 'b', 1, '2022-01-01T00:00:00Z', '2022-01-01T00:00:00Z');
```
but still didn't see it returned by a `...page=a14526...` request with my server.

i thought the issue might be string comparison but i tried `select 4120 > '14526';` and got `false`

---

[tag_aliases-a14526.json.txt](https://github.com/danbooru/danbooru/files/9640431/tag_aliases-a14526.json.txt)

**Comment by evazion** [comment]
The `tag_aliases_pkey` index was apparently corrupt. Rebuilding it fixed it.

Danbooru is still running Postgres 14.1 in production. The release notes for 14.2 and 14.4 mention a couple of index corruption bugs that were fixed in those releases that could have caused it. Although one is caused by `REINDEX CONCURRENTLY`, which I haven't used recently, and the other is said to be an "extremely low-probability scenario" involving `VACUUM`. And `pg_amcheck` didn't detect any corruption.

https://www.postgresql.org/docs/release/14.2/
https://www.postgresql.org/docs/release/14.4/

**Comment by nonamethanks** [comment]
Been a few years, so closing this.

**Comment by ghost** [comment]
IIRC was left open because Danbooru still uses Postgres 14 in production.
