### ISSUE TITLE
ActionController::UrlGenerationError in /related_tag.js

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5287]
https://danbooru.donmai.us/related_tag.js returns an error:

```js
console.error({
  "success":false,
  "error":"ActionController::UrlGenerationError",
  "message":"",
  "backtrace":[
    "app/helpers/application_helper.rb:207:in `link_to_wiki'",
    "app/views/related_tags/_current_tags.html.erb:4",
    "app/views/related_tags/show.js.erb:4",
    "app/controllers/application_controller.rb:66:in `respond_with'",
    "app/controllers/related_tags_controller.rb:14:in `show'"
  ]
});

  Danbooru.Utility.error("Unexpected error: ActionController::UrlGenerationError");
```

**Comment by evazion** [comment]
This still returns a double render error because of an unrelated issue.
