### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by Bobby99as** [danbooru/danbooru#5324]
Every time I try to start the server when I followed the directions I get this

```root@vmi1062870:~/danbooru# bundle exec rails server --binding 0.0.0.0
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: already initialized constant Net::NetPrivate::Socket
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
=> Booting Puma
=> Rails 7.0.4 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
        56: from bin/rails:4:in `<main>'
        55: from /var/lib/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        54: from /var/lib/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        53: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
        52: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
        51: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
        50: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
        49: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
        48: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
        47: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
        46: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `tap'
        45: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        44: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:36:in `start'
        43: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        42: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
        41: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
        40: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        39: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
        38: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
        37: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
        36: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
        35: from config.ru:3:in `block in <main>'
        34: from /var/lib/gems/2.7.0/gems/dead_end-4.0.0/lib/dead_end/core_ext.rb:82:in `require_relative'
        33: from /var/lib/gems/2.7.0/gems/elastic-apm-4.5.1/lib/elastic_apm/spies.rb:111:in `require'
        32: from /var/lib/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        31: from /var/lib/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        30: from /root/danbooru/config/environment.rb:5:in `<main>'
        29: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
        28: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
        27: from /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        26: from /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        25: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        24: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
        23: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
        22: from /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        21: from /usr/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
        20: from /usr/lib/ruby/2.7.0/tsort.rb:415:in `call'
        19: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
        18: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
        17: from /usr/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        16: from /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        15: from /usr/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        14: from /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        13: from /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        12: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
        11: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
        10: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
         9: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
         8: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
         7: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
         6: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
         5: from /var/lib/gems/2.7.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
         4: from /var/lib/gems/2.7.0/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
         3: from /var/lib/gems/2.7.0/gems/dead_end-4.0.0/lib/dead_end/core_ext.rb:65:in `load'
         2: from /var/lib/gems/2.7.0/gems/dead_end-4.0.0/lib/dead_end/core_ext.rb:65:in `load'
         1: from /root/danbooru/config/initializers/core_extensions.rb:106:in `<main>'
/root/danbooru/config/initializers/core_extensions.rb:106:in `alias_method': undefined method `name' for class `Symbol' (NameError)
root@vmi1062870:~/danbooru#```

**Comment by nonamethanks** [comment]
Are you launching it with mounted dirs? If yes, did you pull the latest git master?

**Comment by Bobby99as** [comment]
I'm using the latest GitHub pull

**Comment by Bobby99as** [comment]
I followed what was in this https://github.com/danbooru/danbooru/wiki/Ubuntu-Installation-Help-Guide

**Comment by nonamethanks** [comment]
Ah, for some reason I thought this was docker. I would recommend using the docker compose, that's the supported way to run danbooru. The installation guide is outdated and prone to breakage.

**Comment by Bobby99as** [comment]
Alright thanks I got it up now though is there like a default admin password type thing?

**Comment by nonamethanks** [comment]
The only default account is DanbooruBot, a moderator-level account which runs site tasks. The first user you manually create will have owner role automatically assigned.

**Comment by Bobby99as** [comment]
Alright thanks just one more question how do I stop this site from using localhost to load the image because it should be pointing back to the domain as the location to load the images from

**Comment by nonamethanks** [comment]
See this:
https://github.com/danbooru/danbooru/blob/2341d8341d565c3bbf54a9d3f76e695745e1e7c9/docker-compose.yaml#L35-L38
