### ISSUE TITLE
Database timing out while going through pages

### ISSUE THREAD

**Issue by xHarlock** [danbooru/danbooru#5423]
Error message:
```
{"success":false,"error":"ActiveRecord::QueryCanceled","message":"The database timed out running your query.","backtrace":["app/logical/post_query_builder.rb:175:in `paginated_posts'","app/logical/post_query.rb:86:in `paginated_posts'","app/logical/post_sets/post.rb:110:in `posts'","app/controllers/posts_controller.rb:24:in `index'"]}
```

Links I was using that lead to the error:
* `https://danbooru.donmai.us/posts.json?limit=100&tags=jojo_no_kimyou_na_bouken&page=1`
* `https://danbooru.donmai.us/posts.json?limit=100&tags=jojo_no_kimyou_na_bouken&page=2`
* `https://danbooru.donmai.us/posts.json?limit=100&tags=jojo_no_kimyou_na_bouken&page=3`
* `https://danbooru.donmai.us/posts.json?limit=100&tags=jojo_no_kimyou_na_bouken&page=4`

The first three links worked fine, and I got all the posts. The fourth link however lead to a 500 Internal server error with the above error body.

**Comment by nonamethanks** [comment]
This doesn't seem to happen anymore for those links. There's still slow searches all around but not much use in having an issue like this open.
