### ISSUE TITLE
Issues running script 083_generate_media_asset_variants.rb

### ISSUE THREAD

**Issue by Iratu2** [danbooru/danbooru#5433]
Finally updated to the latest version after 2~ years, running into this error running the script to create the other thumbnail sizes
```
/home/danbooru/danbooru/app/logical/media_file.rb:221:in `preview!': NotImplementedError (NotImplementedError)
        from /home/danbooru/danbooru/app/models/media_asset.rb:108:in `convert_file'
        from /home/danbooru/danbooru/app/models/media_asset.rb:74:in `store_file!'
        from 083_generate_media_asset_variants.rb:7:in `block in <main>'
        from /home/danbooru/danbooru/app/models/application_record.rb:240:in `block (3 levels) in parallel_each'
        from /home/danbooru/danbooru/app/logical/current_user.rb:29:in `block in scoped'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/current_attributes.rb:205:in `set'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/current_attributes.rb:147:in `set'
        from /home/danbooru/danbooru/app/logical/current_user.rb:28:in `scoped'
        from /home/danbooru/danbooru/app/models/application_record.rb:239:in `block (2 levels) in parallel_each'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:238:in `each'
        from /home/danbooru/danbooru/app/models/application_record.rb:235:in `block in parallel_each'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/batches.rb:245:in `block in in_batches'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/batches.rb:229:in `loop'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/batches.rb:229:in `in_batches'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/batches.rb:137:in `find_in_batches'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/querying.rb:22:in `find_in_batches'
        from /home/danbooru/danbooru/app/models/application_record.rb:234:in `parallel_each'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/delegation.rb:108:in `public_send'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/delegation.rb:108:in `block in method_missing'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation.rb:881:in `_scoping'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation.rb:428:in `scoping'
        from /home/danbooru/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/relation/delegation.rb:108:in `method_missing'
        from 083_generate_media_asset_variants.rb:5:in `<main>'
```
Anything I can do to fix this issue?

**Comment by Iratu2** [comment]
Not sure what I've done after a few hours of fixing other bugs and weirdness caused by updating it runs fine so far.
