### ISSUE TITLE
Search order:child_count, Unexpected error: ActiveRecord::StatementInvalid.

### ISSUE THREAD

**Issue by red-tails** [danbooru/danbooru#5542]
If I search for `age:<1year order:child_count`, it gives the following error: `Unexpected error: ActiveRecord::StatementInvalid.`

URL: https://danbooru.donmai.us/posts?tags=order%3Achild_count++limit%3A1+age%3A%3C1year

```ruby
ActiveRecord::StatementInvalid exception raised
app/logical/post_query_builder.rb:173:in `paginated_posts'
app/logical/post_query.rb:86:in `paginated_posts'
app/logical/post_sets/post.rb:109:in `posts'
app/controllers/posts_controller.rb:24:in `index'
app/logical/rack_server_timing.rb:18:in `call'
```

Also I think that child_count isn't indexed? it's a very slow search type

**Comment by red-tails** [comment]
I just got the same `Unexpected error: ActiveRecord::StatementInvalid.` searching for `highres order:mpixels_asc`

URL: https://danbooru.donmai.us/posts?tags=highres+order%3Ampixels_asc+&z=5

```ruby
ActiveRecord::StatementInvalid exception raised
app/logical/post_query_builder.rb:173:in `paginated_posts'
app/logical/post_query.rb:86:in `paginated_posts'
app/logical/post_sets/post.rb:109:in `posts'
app/controllers/posts_controller.rb:24:in `index'
app/logical/rack_server_timing.rb:18:in `call'
```

**Comment by BrokenEagle** [comment]
It's probably related, but `child_count:>10 age:<1year` has a similar error.
