### ISSUE TITLE
`icc_transform: unable to load or find any compatible input profile (Vips::Error)`

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#5667]
Got this error when trying to upload. It may be related to issue #5489.

https://danbooru.donmai.us/uploads/37723270.json

```
Upload failed: 3 errors
icc_transform: unable to load or find any compatible input profile (Vips::Error) 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/operation.rb:228:in `build' 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/operation.rb:481:in `call' 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/image.rb:229:in `method_missing' 
/danbooru/app/logical/media_file/image.rb:8:in `thumbnail_image' 
/danbooru/app/logical/media_file/image.rb:138:in `resize!' 
/danbooru/app/logical/media_file/image.rb:174:in `preview!' 
/danbooru/app/models/media_asset.rb:120:in `convert_file' 
/danbooru/app/models/media_asset.rb:88:in `store_file!' 
/danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' 
icc_transform: unable to load or find any compatible input profile (Vips::Error) 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/operation.rb:228:in `build' 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/operation.rb:481:in `call' 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/image.rb:229:in `method_missing' 
/danbooru/app/logical/media_file/image.rb:8:in `thumbnail_image' 
/danbooru/app/logical/media_file/image.rb:138:in `resize!' 
/danbooru/app/logical/media_file/image.rb:174:in `preview!' 
/danbooru/app/models/media_asset.rb:122:in `convert_file' 
/danbooru/app/models/media_asset.rb:88:in `store_file!' 
/danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' 
icc_transform: unable to load or find any compatible input profile (Vips::Error) 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/operation.rb:228:in `build' 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/operation.rb:481:in `call' 
/home/danbooru/bundle/gems/ruby-vips-2.2.1/lib/vips/image.rb:229:in `method_missing' 
/danbooru/app/logical/media_file/image.rb:8:in `thumbnail_image' 
/danbooru/app/logical/media_file/image.rb:138:in `resize!' 
/danbooru/app/logical/media_file/image.rb:174:in `preview!' 
/danbooru/app/models/media_asset.rb:124:in `convert_file' 
/danbooru/app/models/media_asset.rb:88:in `store_file!' 
/danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' 
/home/danbooru/bundle/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
```

The following image is what was causing the above error to trigger.

https://cho-animedia.jp/imgs/p/usvA95G_PvGjGchefBePwQTN9cDBwsPExcbH/122407.jpg

I'm not sure if it's there's something wrong with the image, or something wrong with the Ruby gems.

Do I need to resave the image and upload that or what?

**Comment by nonamethanks** [comment]
This is fixed in vips 8.18.5.
