### ISSUE TITLE
Emoji autocomplete causes 500 Internal Server Error when writing links

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5691]
Mildly annoying. Typing `"a":[` produces the following error:

RegexpError at /autocomplete
============================

premature end of char-class: /[/i

app/logical/autocomplete_service.rb, line 384
---------------------------------------------

``` ruby
  379     # @return [Array<Hash>] the autocomplete results
  380     def autocomplete_emoji(emoji)
  381       normalized_emoji = emoji.downcase.chomp(":")
  382       emojis = Danbooru.config.dtext_emojis.keys
  383   
> 384       results = emojis.grep(/#{normalized_emoji}/i).sort_by do |match|
  385         exact = match.casecmp?(normalized_emoji) ? 1 : 0
  386         prefix = match.downcase.starts_with?(normalized_emoji) ? 1 : 0
  387   
  388         # Sort exact name matches first, then prefix matches, then sort by name.
  389         [-exact, -prefix, match]
```

App backtrace
-------------

 - app/logical/autocomplete_service.rb:384:in `autocomplete_emoji'
 - app/logical/autocomplete_service.rb:78:in `autocomplete_results'
 - app/controllers/autocomplete_controller.rb:12:in `index'
 - app/logical/rack_server_timing.rb:19:in `call'

**Comment by ghost** [comment]
Seems this was fixed by 1f19f90088eda70ee52e77c4b46c7cd3a1823bca.
