### ISSUE TITLE
Read-only filesystem error is not obvious

### ISSUE THREAD

**Issue by megum1n** [danbooru/danbooru#5829]
https://github.com/danbooru/danbooru/discussions/5828

I made filesystem for danbooru container read-only by my own stupidity and I couldn't upload new images.
The problem is that I couldn't see the actual error message because it was too big - danbooru couldn't even insert it into the database.

Suggestions:
- Change index for error column to use md5 hash instead of the whole text (better IMO)
- Set max error message size and truncate all errors if they exceed max size

Danbooru logs:
```
[85281c26-812f-4116-9814-a3d21bddb0c1] ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

app/models/upload.rb:182:in `rescue in process_upload!'
app/models/upload.rb:171:in `process_upload!'
app/models/upload.rb:163:in `async_process_upload!'
app/controllers/uploads_controller.rb:14:in `create'
app/logical/rack_server_timing.rb:19:in `call'
```

Database logs:
```
2024-09-28 04:03:27.768 UTC [219] ERROR:  index row size 3784 exceeds btree version 4 maximum 2704 for index "index_uploads_on_error"
2024-09-28 04:03:27.768 UTC [219] DETAIL:  Index row references tuple (489,52) in relation "uploads".
2024-09-28 04:03:27.768 UTC [219] HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
	Consider a function index of an MD5 hash of the value, or use full text indexing.
2024-09-28 04:03:27.768 UTC [219] STATEMENT:  UPDATE "uploads" SET "status" = $1, "updated_at" = $2, "error" = $3 WHERE "uploads"."id" = $4
2024-09-28 04:03:27.777 UTC [219] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2024-09-28 04:03:27.777 UTC [219] STATEMENT:  UPDATE "upload_media_assets" SET "updated_at" = $1, "error" = $2 WHERE "upload_media_assets"."id" = $3
2024-09-28 04:03:27.778 UTC [219] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2024-09-28 04:03:27.778 UTC [219] STATEMENT:  SET statement_timeout = 9000
2024-09-28 04:03:27.781 UTC [219] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2024-09-28 04:03:27.781 UTC [219] STATEMENT:  UPDATE "uploads" SET "status" = $1, "updated_at" = $2, "error" = $3 WHERE "uploads"."id" = $4
```

**Comment by nottalulah** [comment]
I don't think using an MD5 hash for the index would be particularly useful. GIN indices are typically used for text search (https://www.postgresql.org/docs/current/textsearch-indexes.html), whereas an MD5-based index cannot be used for that purpose.
