### ISSUE TITLE
CookieOverflow exception when replacing post

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#5859]
Attempting to replace [post #8387686](https://danbooru.donmai.us/posts/8387686) by either [URL](https://www.deviantart.com/ikkimay/art/Ying-in-tights-and-a-bikini-894771058) or the "Free download" file from my computer yields:

```
An unexpected error has occurred.

Details: ActionDispatch::Cookies::CookieOverflow exception raised.

app/logical/rack_server_timing.rb:19:in `call'
```

Attempting to upload the target file (again, from both URL and from file) yields:

```
Upload failed: 5 errors Net::SFTP::StatusException open /srv/images/180x180/eb/70/eb70e9eccbff3eeef017e48701b357b5.jpg-7beb5792-84b9-4c14-953f-db4b3e066f20.tmp (4, "failure") (Net::SFTP::StatusException) /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/operations/upload.rb:321:in `on_open' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/request.rb:87:in `respond_to' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:950:in `dispatch_request' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:913:in `when_channel_polled' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/channel.rb:325:in `process' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:540:in `each' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:540:in `each_channel' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:250:in `ev_preprocess' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/event_loop.rb:104:in `each' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/event_loop.rb:104:in `ev_preprocess' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/event_loop.rb:28:in `process' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:226:in `process' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:179:in `block in loop' :187:in `loop' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:179:in `loop' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:804:in `loop' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/operations/upload.rb:203:in `wait' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:105:in `upload!' /danbooru/app/logical/storage_manager/sftp.rb:103:in `upload!' /danbooru/app/logical/storage_manager/sftp.rb:48:in `block in store' /danbooru/app/logical/storage_manager/sftp.rb:83:in `block in with_connection' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with' /danbooru/app/logical/storage_manager/sftp.rb:81:in `with_connection' /danbooru/app/logical/storage_manager/sftp.rb:45:in `store' /danbooru/app/logical/storage_manager/mirror.rb:14:in `block in store' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!' /danbooru/app/logical/danbooru/enumerable.rb:17:in `parallel_each' /danbooru/app/logical/storage_manager/mirror.rb:13:in `store' /danbooru/app/models/media_asset.rb:89:in `store_file!' /danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' Net::SFTP::StatusException open /srv/images/360x360/eb/70/eb70e9eccbff3eeef017e48701b357b5.jpg-dfd58468-ce79-4a88-8a68-bef000a99b61.tmp (4, "failure") (Net::SFTP::StatusException) /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/operations/upload.rb:321:in `on_open' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/request.rb:87:in `respond_to' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:950:in `dispatch_request' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:913:in `when_channel_polled' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/channel.rb:325:in `process' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:540:in `each' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:540:in `each_channel' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:250:in `ev_preprocess' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/event_loop.rb:104:in `each' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/event_loop.rb:104:in `ev_preprocess' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/event_loop.rb:28:in `process' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:226:in `process' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:179:in `block in loop' :187:in `loop' /home/danbooru/bundle/gems/net-ssh-7.2.3/lib/net/ssh/connection/session.rb:179:in `loop' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:804:in `loop' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/operations/upload.rb:203:in `wait' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:105:in `upload!' /danbooru/app/logical/storage_manager/sftp.rb:103:in `upload!' /danbooru/app/logical/storage_manager/sftp.rb:48:in `block in store' /danbooru/app/logical/storage_manager/sftp.rb:83:in `block in with_connection' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with' /danbooru/app/logical/storage_manager/sftp.rb:81:in `with_connection' /danbooru/app/logical/storage_manager/sftp.rb:45:in `store' /danbooru/app/logical/storage_manager/mirror.rb:14:in `block in store' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!' /danbooru/app/logical/danbooru/enumerable.rb:17:in `parallel_each' /danbooru/app/logical/storage_manager/mirror.rb:13:in `store' /danbooru/app/models/media_asset.rb:89:in `store_file!' /danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' Net::SFTP::StatusException (4, "failure") (Net::SFTP::StatusException) /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:848:in `wait_for' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:500:in `mkdir!' /danbooru/app/logical/storage_manager/sftp.rb:140:in `mkdir_f!' /danbooru/app/logical/storage_manager/sftp.rb:134:in `block in mkdir_p!' /danbooru/app/logical/storage_manager/sftp.rb:132:in `each' /danbooru/app/logical/storage_manager/sftp.rb:132:in `mkdir_p!' /danbooru/app/logical/storage_manager/sftp.rb:46:in `block in store' /danbooru/app/logical/storage_manager/sftp.rb:83:in `block in with_connection' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with' /danbooru/app/logical/storage_manager/sftp.rb:81:in `with_connection' /danbooru/app/logical/storage_manager/sftp.rb:45:in `store' /danbooru/app/logical/storage_manager/mirror.rb:14:in `block in store' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!' /danbooru/app/logical/danbooru/enumerable.rb:17:in `parallel_each' /danbooru/app/logical/storage_manager/mirror.rb:13:in `store' /danbooru/app/models/media_asset.rb:89:in `store_file!' /danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' Net::SFTP::StatusException (4, "failure") (Net::SFTP::StatusException) /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:848:in `wait_for' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:500:in `mkdir!' /danbooru/app/logical/storage_manager/sftp.rb:140:in `mkdir_f!' /danbooru/app/logical/storage_manager/sftp.rb:134:in `block in mkdir_p!' /danbooru/app/logical/storage_manager/sftp.rb:132:in `each' /danbooru/app/logical/storage_manager/sftp.rb:132:in `mkdir_p!' /danbooru/app/logical/storage_manager/sftp.rb:46:in `block in store' /danbooru/app/logical/storage_manager/sftp.rb:83:in `block in with_connection' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with' /danbooru/app/logical/storage_manager/sftp.rb:81:in `with_connection' /danbooru/app/logical/storage_manager/sftp.rb:45:in `store' /danbooru/app/logical/storage_manager/mirror.rb:14:in `block in store' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!' /danbooru/app/logical/danbooru/enumerable.rb:17:in `parallel_each' /danbooru/app/logical/storage_manager/mirror.rb:13:in `store' /danbooru/app/models/media_asset.rb:89:in `store_file!' /danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' Net::SFTP::StatusException (4, "failure") (Net::SFTP::StatusException) /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:848:in `wait_for' /home/danbooru/bundle/gems/net-sftp-4.0.0/lib/net/sftp/session.rb:500:in `mkdir!' /danbooru/app/logical/storage_manager/sftp.rb:140:in `mkdir_f!' /danbooru/app/logical/storage_manager/sftp.rb:134:in `block in mkdir_p!' /danbooru/app/logical/storage_manager/sftp.rb:132:in `each' /danbooru/app/logical/storage_manager/sftp.rb:132:in `mkdir_p!' /danbooru/app/logical/storage_manager/sftp.rb:46:in `block in store' /danbooru/app/logical/storage_manager/sftp.rb:83:in `block in with_connection' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt' /home/danbooru/bundle/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with' /danbooru/app/logical/storage_manager/sftp.rb:81:in `with_connection' /danbooru/app/logical/storage_manager/sftp.rb:45:in `store' /danbooru/app/logical/storage_manager/mirror.rb:14:in `block in store' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!' /danbooru/app/logical/danbooru/enumerable.rb:17:in `parallel_each' /danbooru/app/logical/storage_manager/mirror.rb:13:in `store' /danbooru/app/models/media_asset.rb:89:in `store_file!' /danbooru/app/models/media_asset.rb:466:in `block in distribute_files!' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/promises.rb:1776:in `block in on_resolvable' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker' :187:in `loop' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch' /home/danbooru/bundle/gems/concurrent-ruby-1.3.1/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'.
```

**Comment by RaisingK** [comment]
Replacement works now, but I'll let someone else close it in case it represents a problem that can be fixed..,

**Comment by nonamethanks** [comment]
Sounds like a problem similar to https://github.com/danbooru/danbooru/issues/5752

**Comment by nottalulah** [comment]
If there's an exception when replacing it dumps the exception message into the replacement errors

https://github.com/danbooru/danbooru/blob/f4960115f306ab7aba21b8daedea44f2e85cde8c/app/logical/post_replacement_processor.rb#L55-L56

which gets put into a flash

https://github.com/danbooru/danbooru/blob/f4960115f306ab7aba21b8daedea44f2e85cde8c/app/controllers/post_replacements_controller.rb#L15-L16

The error given in OP is 22K which is well above the 4K allowed in a cookie. I don't think replacements happen asynchronously, so it may be sufficient to render the error in a create.js.erb file instead—see how it's handled on forum post votes, for example:

https://github.com/danbooru/danbooru/blob/f4960115f306ab7aba21b8daedea44f2e85cde8c/app/views/forum_post_votes/create.js.erb#L1-L3
